### ISSUE TITLE
Error running az webapp

### ISSUE THREAD

**Issue by verricoi** [Azure/azure-cli#10269]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
[Errno 2] No such file or directory: '/home/azureuser/mslearn-secure-app-with-oidc-and-azure-ad/WebApp-OpenIDConnect-DotNet.csproj'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/xml/etree/ElementTree.py, ln 1196, in parse
    tree.parse(source, parser)
python3.6/xml/etree/ElementTree.py, ln 586, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/azureuser/mslearn-secure-app-with-oidc-and-azure-ad/WebApp-OpenIDConnect-DotNet.csproj'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --resource-group {} --sku {} --name {}`

## Environment Summary
```
Linux-4.15.0-1052-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.71

```

**Comment by btardif** [comment]
We are investigating this issue

**Comment by panchagnula** [comment]
closing this because of the lack of response, Please re-open if you are still see this with the latest version of CLI

**Comment by knobel-dk** [comment]
I am seeing this with version `2.0.75-1~xenial` too running Ubuntu 16.04 issuing:

```
sudo apt-get install libssl-dev libcurl4-openssl-dev python3-dev gcc libmpc-dev
python -m pip install --upgrade pip
pip install -r requirements.txt
sudo apt-get update && sudo apt-get install --only-upgrade -y azure-cli
az webapp up -n lift-churn-predictor
```

**Comment by panchagnula** [comment]
Note the az webapp up command always needs to run from the context of the DIR the code to be deployed is located in the original issue that was the cause. Given you are running it via Devops make sure the command runs from the context of the code.

**Comment by knobel-dk** [comment]
> Note the az webapp up command always needs to run from the context of the DIR the code to be deployed is located in the original issue that was the cause. Given you are running it via Devops make sure the command runs from the context of the code.

Thanks for the quick reply. Hmm.. Here is the YAML for the given task. Note that `workingDirectory: web` is the 
```
steps:
- task: AzureCLI@1
  displayName: 'Azure CLI '
  inputs:
    azureSubscription: pipeline
    scriptLocation: inlineScript
    inlineScript: 'sudo apt-get update && sudo apt-get install --only-upgrade -y azure-cli && az webapp up --name "lift-churn-predictor" --resource-group "AI-WestEurope-Lift" --location "West Europe"'
    workingDirectory: web
```

The contents of the folder `web` is almost identical to [this](https://github.com/Azure-Samples/python-docs-hello-world) folder, which is used in your [quickstart](https://docs.microsoft.com/en-gb/azure/app-service/containers/quickstart-python).

Thanks again for the quick reply - I am curious to hear your reply.
