### ISSUE TITLE
aks browse: Ingress page Endpoints collumn has blocked links

### ISSUE THREAD

**Issue by martinvelos** [Azure/azure-cli#10321]
## Describe the bug

**Command Name**
`az aks browse`

**Errors:**
When in http://127.0.0.1:8001/#!/ingress?namespace=_all clicking any of the icons bellow "Endpoints" leads to [about:blank#blocked](about:blank#blocked) which is of no use.

## Environment Summary
```
Linux-5.1.6-200.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine
Python 2.7.16
Shell: bash
azure-cli 2.0.71

```
## Additional Context
Made with a yaml with
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: _RESOURCE_NAME_
  namespace: _NAMESPACE_
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: _DNS_NAME_
    http:
      paths:
      - backend:
          serviceName: _SERVICE_NAME_
          servicePort: _SERVICE_PORT_
        path: /(.*)
```
