### ISSUE TITLE
az resource-graph --include displayNames fails on ubuntu

### ISSUE THREAD

**Issue by ChendrayanV** [Azure/azure-cli#11652]
## Describe the bug
az resource-graph --include displayNames fails on ubuntu, below is my Az pipeline 
```yml
trigger:
  branches:
    include:
      - '*'
stages:
  - stage: 
    jobs:
      - job: 
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: 'SERVICECONNECTION'
              scriptLocation: inlineScript
              inlineScript: | 
                az extension add --name resource-graph
                az graph query -q "where type =~ 'Microsoft.Compute/virtualMachines' | project id" --include displayNames
**Warning:**
**_WARNING: Failed to include displayNames to result. Error: 'displayName'_**

**Works fine in windows-latest**
```yml
trigger:
  branches:
    include:
      - '*'
stages:
  - stage: 
    jobs:
      - job: 
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: 'SERVICECONNECTION'
              scriptLocation: inlineScript
              inlineScript: | 
                az extension add --name resource-graph
                az graph query -q "where type =~ 'Microsoft.Compute/virtualMachines' | project id" --include displayNames
```
## Environment Summary
```
Windows-10-10.0.16299-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.74 *

Extensions:
log-analytics 0.1.3
resource-graph 1.0.0

```
