### ISSUE TITLE
az webapp log config --application-logging false doesn't turn it off

### ISSUE THREAD

**Issue by jongio** [Azure/azure-cli#12653]
# Issue
az webapp log config --application-logging false doesn't turn it off

## Default state
![image](https://user-images.githubusercontent.com/2163001/77015501-3368aa00-6932-11ea-8def-2414b3dff649.png)

## Turn on
Run `az webapp log config --application-logging true -n mvpsdkdemoapp -o yaml` to turn on

```yaml
applicationLogs:
  azureBlobStorage:
    level: 'Off'
    retentionInDays: null
    sasUrl: null
  azureTableStorage:
    level: 'Off'
    sasUrl: null
  fileSystem:
    level: Error
detailedErrorMessages:
  enabled: false
failedRequestsTracing:
  enabled: false
httpLogs:
  azureBlobStorage:
    enabled: false
    retentionInDays: 7
    sasUrl: null
  fileSystem:
    enabled: false
    retentionInDays: 7
    retentionInMb: 100
id: /subscriptions/25fd0362-aa79-488b-b37b-d6e892009fdf/resourceGroups/mvpsdkdemorg/providers/Microsoft.Web/sites/mvpsdkdemoapp/config/logs
kind: null
location: West US
name: logs
resourceGroup: mvpsdkdemorg
type: Microsoft.Web/sites/config
```

## Turn off

To turn off I run the following:
`az webapp log config --application-logging false -n mvpsdkdemoapp -o yaml`

But the UI doesn't show it as disabled:

![image](https://user-images.githubusercontent.com/2163001/77016061-d837b700-6933-11ea-9691-22beb9f28572.png)

and the same output is returned.

```yaml
applicationLogs:
  azureBlobStorage:
    level: 'Off'
    retentionInDays: null
    sasUrl: null
  azureTableStorage:
    level: 'Off'
    sasUrl: null
  fileSystem:
    level: Error
detailedErrorMessages:
  enabled: false
failedRequestsTracing:
  enabled: false
httpLogs:
  azureBlobStorage:
    enabled: false
    retentionInDays: 7
    sasUrl: null
  fileSystem:
    enabled: false
    retentionInDays: 7
    retentionInMb: 100
id: /subscriptions/25fd0362-aa79-488b-b37b-d6e892009fdf/resourceGroups/mvpsdkdemorg/providers/Microsoft.Web/sites/mvpsdkdemoapp/config/logs
kind: null
location: West US
name: logs
resourceGroup: mvpsdkdemorg
type: Microsoft.Web/sites/config
```

> Please note that the applicationLogging: fileSystem only has "level", it doesn't have have "enabled"

# CLI version

```azure-cli                          2.2.0

command-modules-nspkg              2.0.3
core                               2.2.0
nspkg                              3.0.4
telemetry                          1.0.4

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'     Extensions directory 'C:\Users\JonGallant\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
```

azsdke2e
