### ISSUE TITLE
az functionapp Azure Cli deploy error (v2)

### ISSUE THREAD

**Issue by allschu** [Azure/azure-cli#13655]
## Describe the bug

**Command Name**
`az functionapp deployment source config-zip`

**Errors:**
```
HTTPSConnectionPool(host='*************.azurewebsites.net', port=443): Read timed out. (read timeout=3)
Traceback (most recent call last):
python3.6/site-packages/urllib3/connectionpool.py, ln 387, in _make_request
    six.raise_from(e, None)
<string>, ln 2, in raise_from
python3.6/site-packages/urllib3/connectionpool.py, ln 383, in _make_request
    httplib_response = conn.getresponse()
lib/python3.6/http/client.py, ln 1331, in getresponse
    response.begin()
...
socket.timeout: The read operation timed out


python3.6/site-packages/requests/adapters.py, ln 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='*****************.scm.azurewebsites.net', port=443): Read timed out. (read timeout=3)
```

## To Reproduce:
Deploy zipped publish package to Azure Function App service. using the following command

`az functionapp deployment source config-zip -g [RESOURCE-GROUP ]-n [ FUNCTION APP NAME] --src publish.zip`

## Environment Summary
```
Linux-4.15.0-1082-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.5.1 *

```

**Comment by yonzhan** [comment]
functionapp

**Comment by jacksinclairaudley** [comment]
We get this problem as well, it can be quite intermittent

**Comment by lobsteropteryx** [comment]
We've seen this as well, intermittantly across many projects.  Have opened an Azure support issue, but we never got this resolved.

**Comment by katerd** [comment]
We're seeing exactly the same read timeout error too. One of our pipelines deploys 5 function apps in sequence, and it's a dice roll if it succeeds. We're considering retry loops for each of the az commands as a workaround.

**Comment by ttjackott** [comment]
> 
> 
> We're seeing exactly the same read timeout error too. One of our pipelines deploys 5 function apps in sequence, and it's a dice roll if it succeeds. We're considering retry loops for each of the az commands as a workaround.

We do exactly that - we retry up to 3 times sometimes to work around this. Here is our workaround powershell which we do via an AzureCLI task in our yaml multi stage pipelines:

```powershell
$resourceGroupName = "...."
$functionAppName = "...."
$artifactPath = "...."

function Deploy-Function {
    return az functionapp deployment source config-zip --resource-group $resourceGroupName --name $functionAppName --src $artifactPath
}

$functionDeploymentResult = $null;
For ($i = 0; $i -lt 3; $i++) {
    Write-Host "Function deployment attempt $($i+1)"

    # successful results are returned as JSON, if this converts to JSON we can assume it is successful
    # failed results do not parse as JSON, so will be null on failure
    $functionDeploymentResult = Deploy-Function | ConvertFrom-Json
    if ($functionDeploymentResult){
        break
    }
    else {
        Write-Host "Function deployment failed at attempt $($i+1)"
    }
}
```

**Comment by arthfl** [comment]
Is there any progress on this issue?
We have failing function deployments all over the place because of this.

**Comment by shuruev** [comment]
Having the same issue, started being worse recently. Not sure what it really depends on.

**Comment by arthfl** [comment]
We found btw. out that (at least for our simple use-case), the app deployment works perfectly fine when you use `az webapp` instead of `az functionapp`.
This makes this whole issue a bit weirder, but maybe this is helping somebody ;-)

**Comment by sonic1981** [comment]
I'm starting to think that this is caused by some timing issue. It seems if you make any changes to the function, the upload basically fails for a period of time. Then it will start working again. This seems like a really poor user experience at best.

I've seen a few posts about proxys. I'm not behind a proxy yet have had this issue for multiple days now. This really needs a fix

**Comment by sonic1981** [comment]
I think I **finally** got to the bottom of this issue. It seems to be a resource problem, kudos to https://github.com/Azure/azure-cli/issues/11980#issuecomment-685823613.

I upgraded my service plan to a premium one and the problem seems to have gone away

**Comment by Splaxi** [comment]
I hit the same issue.

I added the --timeout 360 to my command and it seems to have made a difference.

**Comment by thatscotdatasci** [comment]
Hitting this issue too - already on a premium plan, and unfortunately the timeout argument doesn't appear to have improved anything (doesn't even appear to be being honoured for the call that's hitting the timeout)

**Comment by schaijkw** [comment]
I am facing the exact same issue. --timeout is not respected and I will add a retry loop so we will improve the chance of a succesful deployment.

**Comment by lobsteropteryx** [comment]
This might not be an option for everyone, but using deployment slots fixed this for us--haven't seen the issue again, across multiple function apps.  I am sure I've seen a comment in the documentation from Microsoft that suggests that there may be issues deploying without slots, but I can't seem to find it.

**Comment by schaijkw** [comment]
> This might not be an option for everyone, but using deployment slots fixed this for us--haven't seen the issue again, across multiple function apps. I am sure I've seen a comment in the documentation from Microsoft that suggests that there may be issues deploying without slots, but I can't seem to find it.

Are you reusing the same slot everytime? I create a unique slot (staging_{{buildid}}) for a release and after success I delete the slot. In that case I am always sure I have a clean set of app settings.

**Comment by lobsteropteryx** [comment]
Yes, we reuse the same slot for each deployment, then do a swap.

**Comment by schaijkw** [comment]
> Yes, we reuse the same slot for each deployment, then do a swap.

I tried reuse the same slot. Unfortunately this didn't affect the outcome. Even if the slot already exists and is reused the timeout occurs.

**Comment by byteknacker** [comment]
Having a similar issue, I am using Gitlab to deploy my Function App using az cli commands. It started two days ago but worked fine until then.

**Comment by byteknacker** [comment]
> We found btw. out that (at least for our simple use-case), the app deployment works perfectly fine when you use `az webapp` instead of `az functionapp`.
> This makes this whole issue a bit weirder, but maybe this is helping somebody ;-)

This workaround with webapp works for me. But I hope there is another more standard way. Will this be fixed in the next releases?

**Comment by coppercosmo** [comment]
Has this been fixed? The only way we get this to work is to fail on the first deployment with the above error, and then the subsequent deployments work. I assume it's because the scm website appsettings aren't needing to be updated while a deployment is happening like during the first deployment.

The `az webapp` "fix" will not work for me, because I need them to be functionapps and not webapps.

**Comment by askaribragimov** [comment]
and yet another azure issue. Subscribing for updates.

**Comment by peterkarman1** [comment]
same issue on webapps.....

**Comment by byteknacker** [comment]
Any update on this?

**Comment by sylnsr** [comment]
FWIW, another reason the `az webapp` fix is not applicable is that some folks need the `--build-remote` option, which `az webapp` does not support.

**Comment by pinakighatak** [comment]
Not sure this is relevant today in 2022 - since there are native GitHub actions to do this, that works fantastically well. Here is an example:
````yaml
# Deploy template
- name: Provision Azure Function App from Bicep
  id: functiondeploy
  uses: Azure/arm-deploy@v1
  env:
    DEPLOYMENT_NAME: FunctionDeploy-${{github.run_number}}
  with:
    resourceGroupName: ${{ inputs.targetResourceGroup }}

    template: ${{ inputs.buildOutputPath }}/bicep/main.bicep
    parameters: initiator=${{github.actor}}
    deploymentMode: Incremental
    deploymentName: ${{env.DEPLOYMENT_NAME}}


- name: Deploy Function App code
  uses: Azure/functions-action@v1
  with:
    app-name: ${{ steps.functiondeploy.outputs.functionName}}
    package: ${{ inputs.buildOutputPath }}/build

- name: Show Function deployment outputs
  run: |
   echo "function Name: ${{ steps.functiondeploy.outputs.functionName }}"
   echo "function Swagger URL: ${{ steps.functiondeploy.outputs.functionSwaggerURL }}"
   echo "function-URL=${{ steps.functiondeploy.outputs.functionSwaggerURL }}" >> $GITHUB_ENV
````
