### ISSUE TITLE
`az acs create` with kubernetes appends "-k8s-masters" to various names

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1441]
`-k8s-masters` is appended to lots of things, including the cluster name.

This causes the main load balancer to be very misleadingly labeled (includes `-k8s-masters` in the name despite targeting agent nodes), and causes weirdness such as the following, whenever I choose to use `colemick-k8s-deis1` as the cluster/rg name:

```
contexts:
- context:
    cluster: "colemick-k8s-deis1-k8s-masters"
    user: "colemick-k8s-deis1-k8s-masters-admin"
  name: "colemick-k8s-deis1-k8s-masters"
current-context: "colemick-k8s-deis1-k8s-masters" 
```

This isn't needed. I don't have to do anything like this when using acs-engine.

cc: @brendandburns
