### ISSUE TITLE
Command "az storage blob sync" doesn't work with managed identity

### ISSUE THREAD

**Issue by sabretus** [Azure/azure-cli#16071]
## Describe the bug

**Command Name**
`az storage blob sync`

**Errors:**
```
MSI auth not yet supported.
Traceback (most recent call last):
command_modules/storage/azcopy/util.py, ln 119, in client_auth_for_azcopy
    token_info = _unserialize_non_msi_token_payload(token_info)
command_modules/storage/azcopy/util.py, ln 142, in _unserialize_non_msi_token_payload
    parsed_authority = urlparse(token_info['_authority'])
KeyError: '_authority'

...

command_modules/storage/azcopy/util.py, ln 121, in client_auth_for_azcopy
    raise Exception('MSI auth not yet supported.')
Exception: MSI auth not yet supported.
```

## To Reproduce:

- `az login --identity`
```
[
  {
    "environmentName": "AzureCloud",
    "homeTenantId": "XXX",
    "id": "XXX",
    "isDefault": true,
    "managedByTenants": [],
    "name": "Some name",
    "state": "Enabled",
    "tenantId": "XXX",
    "user": {
      "assignedIdentityInfo": "MSI",
      "name": "systemAssignedIdentity",
      "type": "servicePrincipal"
    }
  }
]
```
- `az storage blob sync --account-name {storage account name} -c {container name} -s ./myFile.txt -d myFile.txt --auth-mode login`

## Expected Behavior
Sync file from local to Azure blob storage
## Environment Summary
```
Linux-5.4.0-1031-azure-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.15.1

```
## Additional Context
Similar subcommand `list` works fine:
`az storage blob list -c {container name} --account-name {storage account name} --auth-mode login`
returns json with information about blobs.

I can also sync files with [azcopy](https://docs.microsoft.com/uk-ua/azure/storage/common/storage-use-azcopy-v10) tool using the same managed identity

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi @sabretus, thanks a lot for your feedback! We will prioritize the work according to bandwidth.
@zezha-msft  Is there an interface to pass AD credential to azcopy?

**Comment by zezha-msft** [comment]
Hi @Juliehzl, yes, AzCopy does have a way of accepting AD credential directly. Let's set up some time to discuss the specifics.

**Comment by Juliehzl** [comment]
> Hi @Juliehzl, yes, AzCopy does have a way of accepting AD credential directly. Let's set up some time to discuss the specifics.

Thanks @zezha-msft!

**Comment by onionhammer** [comment]
Was this work complete? It doesnt appear to work but the issue was closed

**Comment by evelyn-ys** [comment]
@onionhammer It's true that `az blob sync` does not support AAD auth.
You can use `az storage account keys list` to get an account key then run `az blob sync` with `--account-key`

**Comment by onionhammer** [comment]
Not if you disable key based auth on your storage account as a matter of policy, you can't.

**Comment by evelyn-ys** [comment]
Then can you use sas token with `az storage account generate-sas`?😂

**Comment by onionhammer** [comment]
That's an interesting question, but why can't this support login based auth like everything else on this cli command?

**Comment by onionhammer** [comment]
@evelyn-ys Any update? Or are we all happy with az blob sync not working with azure storage accounts without keys?

**Comment by evelyn-ys** [comment]
Sorry but there's some technical issue that CLI supports AAD auth differently with azcopy.

If you have to use AAD auth, please run `azcopy` directly. CLI has already installed `azcopy` for you.

**Comment by onionhammer** [comment]
@evelyn-ys So should this issue be reopened? Seems like it

**Comment by dvasdekis** [comment]
Docs are also incorrect as [docs state](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest)
```
Please specify one of the following authentication parameters for your commands: --auth-mode, --account-key, --connection-string, --sas-token
```
But obviously `--auth-mode login` doesn't work in the case of `az storage account sync` (as compared to [az storage blob copy](https://docs.microsoft.com/en-us/cli/azure/storage/blob/copy?view=azure-cli-latest))

**Comment by chandrasekharpolu** [comment]
I still have a similar issue but with az storage blob directory upload


Traceback (most recent call last):
  File "/home/agentadmin/myagent/_work/_tool/Python/3.8.12/x64/lib/python3.8/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/agentadmin/myagent/_work/_tool/Python/3.8.12/x64/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/home/agentadmin/myagent/_work/_tool/Python/3.8.12/x64/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/agentadmin/myagent/_work/_tool/Python/3.8.12/x64/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/home/agentadmin/myagent/_work/_temp/.azclitask/cliextensions/storage-preview/azext_storage_preview/__init__.py", line 252, in new_handler
    handler(ex)
  File "/home/agentadmin/myagent/_work/_temp/.azclitask/cliextensions/storage-preview/azext_storage_preview/__init__.py", line 194, in handler
    raise ex
  File "/home/agentadmin/myagent/_work/_tool/Python/3.8.12/x64/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/home/agentadmin/myagent/_work/_tool/Python/3.8.12/x64/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/home/agentadmin/myagent/_work/_tool/Python/3.8.12/x64/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/agentadmin/myagent/_work/_temp/.azclitask/cliextensions/storage-preview/azext_storage_preview/operations/azcopy.py", line 19, in storage_blob_upload
    azcopy = _azcopy_blob_client(cmd, client)
  File "/home/agentadmin/myagent/_work/_temp/.azclitask/cliextensions/storage-preview/azext_storage_preview/operations/azcopy.py", line 65, in _azcopy_blob_client
    return AzCopy(creds=blob_client_auth_for_azcopy(cmd, client))
  File "/home/agentadmin/myagent/_work/_temp/.azclitask/cliextensions/storage-preview/azext_storage_preview/azcopy/util.py", line 83, in blob_client_auth_for_azcopy
    raise Exception('MSI auth not yet supported.')
**Exception: MSI auth not yet supported.**

Any one who can help on this?

**Comment by dvasdekis** [comment]
> Sorry but there's some technical issue that CLI supports AAD auth differently with azcopy.
> 
> If you have to use AAD auth, please run `azcopy` directly. CLI has already installed `azcopy` for you.

In Azure Devops, using, this was not correct. We had to use the below approach to install Azcopy inline on a Linux host and then use it.
```yaml
        - task: AzureCLI@2
          displayName: 'Upload repo files to platform-repo container'
          inputs:
            azureSubscription: 'My-Devops-SPN-name'
            scriptType: bash
            scriptLocation: inlineScript
            addSpnToEnvironment: true  # Injects $servicePrincipalId, $servicePrincipalKey, $tenantId
            failOnStandardError: false # Generates false positives on linux
            inlineScript: |
              # Grab the name of the lake that's in the current resource group (e.g. 'laketst' )
              export storageacct=$(az graph query -q "Resources | where type =~ 'Microsoft.Storage/storageAccounts' | where resourceGroup contains 'laketst' | project name "  --query data --output tsv)
              export subscriptionId=$(az graph query -q "ResourceContainers | where resourceGroup contains 'laketst' | project subscriptionId | limit 1" --query data --output tsv)
              az account set --subscription $subscriptionId
              # Makes azcopy available in current directory - download, extract, run
              curl -o azcopy.tar.gz -L https://aka.ms/downloadazcopy-v10-linux
              tar --strip-components=1 --exclude=*.txt -xzvf azcopy.tar.gz
              chmod +x azcopy
              export AZCOPY_SPA_CLIENT_SECRET=$servicePrincipalKey
              ./azcopy login --service-principal --tenant-id $tenantId --application-id $servicePrincipalId
              ./azcopy sync $(Build.SourcesDirectory)  https://$storageacct.blob.core.windows.net/platform-repo --recursive --exclude-pattern="*.git"
 ```

**Comment by dvasdekis** [comment]
It looks like as of now, `az storage blob sync` does work with managed identity. I was able to make it work with:

```
az account set --subscription ${{ env.subscriptionId }}
az storage blob sync --account-name ${{ env.storageacct }} -s "${{ github.workspace }}/platform" -c platform-repo
```
even though it doesn't list an option for `--auth-mode login`

**Comment by stephenhogg-des** [comment]
@onionhammer I work with @dvasdekis - answer is no, unfortunately.

**Comment by dvasdekis** [comment]
Hi @evelyn-ys could you please reopen this issue? It is a critical one for us and, judging by this thread, others. We have separately raised it as an enterprise Azure ticket (Case 2305100030000406) as this product isn't working as documented.

**Comment by evelyn-ys** [comment]
@dvasdekis I'm sorry that there's technical blockers to integrate `azcli` with `azcopy` OAuth. But I don't think it will block any scenario.

Azure CLI has already installed `$HOME/.azcopy/azcopy.exe` for windows and  `~/bin/azcopy` for linux after first run of `az storage blob sync`, so you can run azcopy commands directly using AAD just like you shared before
```
~/bin/azcopy login --service-principal --tenant-id $tenantId --application-id $servicePrincipalId
~/bin/azcopy sync $(Build.SourcesDirectory)  https://$storageacct.blob.core.windows.net/platform-repo --recursive
```

**Comment by stephenhogg-des** [comment]
@evelyn-ys we see the following error when trying to login as you've suggested:

![image](https://github.com/Azure/azure-cli/assets/127154890/f0a40450-61f3-478a-a169-e5126f944acc)

**Comment by evelyn-ys** [comment]
That seems azcopy login issue in Github Actions. What I can provide is an azcopy doc for AAD login https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-authorize-azure-active-directory?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json

For more help, maybe you can create issue to https://github.com/Azure/azure-storage-azcopy repo

**Comment by onionhammer** [comment]
@evelyn-ys even if there is a technical blocker from implementation, this issue should be re-opened or closed as 'not planned' - this is definitely not 'complete' as the status would indicate.

**Comment by tudorpopams** [comment]
Is there any update on this issue? We are blocked by the lack of the `--auth-mode login` flag and as far as I can tell, many people have complained about it since 4 years ago.

**Comment by dvasdekis** [comment]
For those struggling with this limitation while using Github actions, we found that the below allows for sync operations using OpenID Connect:
```yaml
      - name: Install azcopy
        uses: Azure/powershell@v2
        with:
          azPSVersion: latest
          failOnStandardError: true
          errorActionPreference: stop
          inlineScript: |
            # Make sure that errors are caught and the script stops 
            $PSNativeCommandUseErrorActionPreference = $true
            Invoke-WebRequest -Uri "https://aka.ms/downloadazcopy-v10-windows" -OutFile AzCopy.zip -UseBasicParsing
            #Expand Archive
            Expand-Archive ./AzCopy.zip ./AzCopy -Force
            $userenv = [System.Environment]::GetEnvironmentVariable("Path", "User")
            [System.Environment]::SetEnvironmentVariable("PATH", $userenv + ";$pwd.Path", "User")

      - name: Sync repo
        id: uploadsync
        uses: Azure/powershell@v2
        with:
          azPSVersion: latest
          failOnStandardError: true
          errorActionPreference: stop
          inlineScript: |
            # Make sure that errors are caught and the script stops 
            $PSNativeCommandUseErrorActionPreference = $true
            $Env:AZCOPY_AUTO_LOGIN_TYPE="AZCLI"
            $Env:AZCOPY_TENANT_ID="${{ secrets.AZURE_TENANT_ID }}"
            azcopy sync "${{ github.workspace }}/repopath/" "https://mystorageaccount.blob.core.windows.net/mycontainer/" --delete-destination true
```

Not a solution, but a workaround that's fast enough for our purposes.
