### ISSUE TITLE
Can not run docker compose up locally: local path not allowed as volume source

### ISSUE THREAD

**Issue by Zaniyar** [Azure/azure-cli#16773]
I have a simple docker-compose.yaml file:

```
version: '3'
services:
  website:
    image: php:7.4-cli
    container_name: php72
    volumes:
      - ./hello:/var/www/html
    ports:
      - 8000:80
```
I have nothing set up with azure (I am even logged out on the cli) - I just want to run this docker compose locally - nothing to do with Azure:

```
$ docker compose up

cannot get container group client: not logged in to azure, you need to run "docker login azure" first: open /Users/xyz/.azure/dockerAccessToken.json: no such file or directory
```
or sometimes this error:
`
host path ("/Users/xyz/project/hello") not allowed as volume source, you need to reference an Azure File Share defined in the 'volumes' section`

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.7
Installer: HOMEBREW

azure-cli 2.18.0

```

How can I use docker compose just locally without Azure? (the next step is going to be deploy it on Azure, but for now, I just want to test it locally..)
