### ISSUE TITLE
It is not possible to pass azure storage account name and key as a cli parameter when using --file option.

### ISSUE THREAD

**Issue by simon-an** [Azure/azure-cli#17376]
[Enter feedback here]

It is not possible to pass azure storage account name and key as a cli parameter when using --file option.

Example:

```
az container create \
    --resource-group $ACI_PERS_RESOURCE_GROUP \
    --file container.yaml \
    --azure-file-volume-account-key $STORAGE_KEY \
    --azure-file-volume-account-name $ACI_PERS_STORAGE_ACCOUNT_NAME 
```

container.yaml
```yaml
      volumeMounts:
      - mountPath: /config/
        name: configvolume
      - mountPath: /data
        name: datavolume
...
  volumes:
  - name: configvolume
    azureFile:
      sharename: config
  - name: datavolume
    azureFile:
      sharename: data

```

The storageAccountName and storageAccountKey for the azureFile object inside the yaml file should be optional. If omitted they should be overwritten by the "azure-file-volume-account-key" and "azure-file-volume-account-name" cli parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e5d1da7-7c4f-c9e6-e4b9-a30407675acf
* Version Independent ID: ba32e12d-8283-f980-e1d0-1ca2a75a5152
* Content: [az container](https://docs.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/container.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/container.yml)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**
