### ISSUE TITLE
support removing an addess from a pool by the ip address

### ISSUE THREAD

**Issue by mgexm** [Azure/azure-cli#17572]
**Is your feature request related to a problem? Please describe.**

The problem is if you are doing a rolling deploy of more than one VM at a time then there's no gaurantee that "--remove" (as it works by index) actually removed the correct address from the backend pool. 

**Describe the solution you'd like**

Have a version of "az network application-gateway address-pool update" that lets a VM idempotently remove its own address from a backend pool.

**Describe alternatives you've considered**

1) Allow for a "synchronize" keyword in azure devops yaml pipelines 
2) write a service that provides the synchronization around calling "az network application-gateway address-pool update".

**Additional context**

Using this call in a "rolling deploy" was not thought about clearly ! Otherwise "--remove" operate using an IP address !

```
 stage:
    displayName: "Deployment : ${{ parameters.ENVIRONMENT }} Hosted Applications And Tasks"
    jobs:
      - deployment:
        displayName: IIS
        environment:
          name: ${{ parameters.ENVIRONMENT }}
          resourceType: VirtualMachine
        strategy:
          rolling:
            # this effectively starts N number of deployments based on how many machines are currently in the  environment passed into ${{ parameters.ENVIRONMENT }} corresponding to a matching Azure Devops "Environments" entry ... For sake of argument assume the environment has 10 VMs in it.
            maxParallel: 50%
            preDeploy:
              # 
              steps:
                - task: AzureCLI@2
                  displayName: Manage Pooled VM
                  inputs:
                    azureSubscription: "mysub"
                    scriptType: ps
                    scriptLocation: inlineScript
                    inlineScript: |
                      # remove myself from the pool ...
                      $IPAddress = Get-WmiObject Win32_NetworkAdapterConfiguration | Where-Object {$_.Ipaddress.length -gt 1}
                      $myIPAddr = $IPAddress.ipaddress[0]
                      echo "myIPAddr = $myIPAddr"
                      # this is not how remove works BUT IT SHOULD BE !!!! so that ANY VM can take itself out of the backend pool without affecting anyone else !!! 
                      az network application-gateway address-pool update -g $(ResourceGroupName) --gateway-name $(AppGateway) -n $(AddressPoolName) --remove backendAddresses "{\"ip_address\": \"{$myIPAddr}\"}" 
```
