### ISSUE TITLE
az aks RBAC Error : You must be logged in to the server (Unauthorized)

### ISSUE THREAD

**Issue by midaslmg94** [Azure/azure-cli#17624]
**Resource Provider**

- `azure kubernetes service`
- `azure rbac`

**Description of Feature or Work Requested**

Referring to the document below, I connected aks and rbac.
- [AKS-managed Azure Active Directory integration
](https://docs.microsoft.com/en-us/azure/aks/managed-aad)
- [Use Azure RBAC for Kubernetes Authorization (preview)
](https://docs.microsoft.com/en-us/azure/aks/manage-azure-rbac)
- [Control access to cluster resources using Kubernetes role-based access control and Azure Active Directory identities in Azure Kubernetes Service
](https://docs.microsoft.com/en-us/azure/aks/azure-ad-rbac?toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Faks%2Ftoc.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fbread%2Ftoc.json)

I already have Azure Resource Group, so I create new AKS Cluster and join Azure AD Group. Then, AKS was successfully created and could receive the results shown in the document.

```shell
$ az aks create -g cicd -n k8s-rbac --enable-aad --aad-admin-group-object-ids 84e3f2c7-xxxx-xxxx-xxx-xxxxxxxxx --aad-tenant-id 78289cd7-xxxx-xxxx-xxxx-xxxxxxx
The behavior of this command has been altered by the following extension: aks-preview
{- Finished ..
  "aadProfile": {
    "adminGroupObjectIds": [
      "84e3f2c7-xxxx-xxxx-xxxx-xxxxxxx"
    ],
    "clientAppId": null,
    "enableAzureRbac": false,
    "managed": true,
    "serverAppId": null,
    "serverAppSecret": null,
    "tenantId": "78289cd7-xxxx-xxxx-xxxx-xxxxxxxxx"
  },
  "addonProfiles": {
    "KubeDashboard": {
      "config": null,
      "enabled": false,
      "identity": null
    }
  },
.
.

```
After setting up the subscription, I received aks credentials. It was saved in the /.kube/config file.
```shell
$ az account set --subscription 41f7220a-xxxx-xxxx-xxxx-xxxxxxx
$ az aks get-credentials --resource-group cicd --name k8s-rbac
The behavior of this command has been altered by the following extension: aks-preview
Merged "k8s-rbac" as current context in /home/mglee/.kube/config
```

This is /.kube/config 
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUd ...
    server: https://k8s-rbac-cicd-41f722-xxxxxx.hcp.koreacentral.azmk8s.io:443
  name: k8s-rbac
contexts:
- context:
    cluster: k8s-rbac
    user: clusterUser_cicd_k8s-rbac
  name: k8s-rbac
current-context: k8s-rbac
kind: Config
preferences: {}
users:
- name: clusterUser_cicd_k8s-rbac
  user:
    auth-provider:
      config:
        access-token: eyJ0eXAiO....
        apiserver-id: 6dae42f8-xxx-xxxx-xxxx-xxxxxxxx
        client-id: 80faf920-xxxx-xxxx-xxxx-xxxxxx
        environment: AzurePublicCloud
        expires-in: "3599"
        expires-on: "1617953503"
        refresh-token: 0.ASsA....
        tenant-id: 78289cd7-xxxx-xxxx-xxxx-xxxxxxxxx
      name: azure
```
Successful login to Azure Kubernetes Service AAD Client application with code input. I received a message saying, "Login Success in Azure Kubernetes Service AAD Client, You may close the window."

**However, attempting to look up nodes with the kubectl command resulted in a privilege error.**
```shell
$ kubectl get nodes
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code HN8DLBJYL to authenticate.
error: You must be logged in to the server (Unauthorized)
```
In this AKS, my account have `Azure Kubernetes Service Cluster User Role`, `Azure Kubernetes Service Contributor Role` and `Owner`

The IAM has sufficient privileges, but I don't know if there is an error that `error: You must be logged in to the server (Unauthorized)` 

**Current API Version**

This is my current azure, aks version
- az version
```shell
$ az version
{
  "azure-cli": "2.21.0",
  "azure-cli-core": "2.21.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.6"
  }
}
```
- aks version
```shell
$ az aks get-upgrades --resource-group cicd --name k8s-rbac --output table
The behavior of this command has been altered by the following extension: aks-preview

Name     ResourceGroup    MasterVersion    Upgrades
-------  ---------------  ---------------  --------------
default  cicd             1.18.14          1.19.6, 1.19.7
```
