### ISSUE TITLE
az aks get-credentials should have a flag or automatically convert generated config with azure kubelogin

### ISSUE THREAD

**Issue by daniel-anova** [Azure/azure-cli#20511]
**Is your feature request related to a problem? Please describe.**

For AzureAD integrated aks clusters `kubelogin convert-kubeconfig` is required to renew credentials, it's easy to forget/overlook this extra step and have credentials expire making users unable to access the cluster until they do a new `az aks get credentials`.

**Describe the solution you'd like**

It would be a better user experience if `az aks get-credentials` would automatically detect AAD integration and do the conversion step.

**Describe alternatives you've considered**

If  that is unreliable having a flag  such as  `--aad` would also be acceptable.

**Additional context**

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@daniel-anova Apologies for the late reply. We are looking into this ask. We will update this thread once we have more details.

@Azure/aks-pm Could you please provide an update on this ask ? Awaiting your reply.

**Comment by SayakMukhopadhyay** [comment]
This might also be useful in non-interactive scenarios, in which case, the user should be able to tell `get-credentials` to fetch non-interactive `kubelogin` command args.

**Comment by rdtechie** [comment]
Any update?

**Comment by mr-davidc** [comment]
I also think this would be a great improvement. Even something like:

`az aks get-credentials --name <cluster-name> --resource-group <resource-group-name> --msi`

**Comment by patrickdmw** [comment]
Are you looking for the `--format "exec"` option for `az aks get-credentials`?
https://learn.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials

"exec" creates an entry like
```yaml
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      - srv123
      - --client-id
      - usr456
      - --tenant-id
      - tnt789
      - --login
      - devicecode
      command: kubelogin
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

"azure" creates
```yaml
  user:
    auth-provider:
      config:
        access-token: secrettoken
        apiserver-id: aid123
        client-id: cid456
        config-mode: "1"
        environment: AzurePublicCloud
        expires-in: "1234"
        expires-on: "1673275758"
        refresh-token: secretrefreshtoken
        tenant-id: tnt789
      name: azure
```
