### ISSUE TITLE
Cannot retrieve MongoDB information

### ISSUE THREAD

**Issue by khusseini** [Azure/azure-cli#21203]
## Describe the bug

**Command Name**
`az cosmosdb mongodb database`

**Errors:**
```
The operation 'azure.mgmt.cosmosdb.operations#MongoDBResourcesOperations.delete_mongo_db_database' is invalid.
Traceback (most recent call last):
azure/cli/core/__init__.py, ln 831, in get_op_handler
    op = getattr(op, part)
AttributeError: type object 'MongoDBResourcesOperations' has no attribute 'delete_mongo_db_database'

...

azure/cli/core/__init__.py, ln 836, in get_op_handler
    raise ValueError("The operation '{}' is invalid.".format(operation))
ValueError: The operation 'azure.mgmt.cosmosdb.operations#MongoDBResourcesOperations.delete_mongo_db_database' is invalid.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az cosmosdb mongodb database --help`

## Environment Summary
```
Linux-5.13.0-28-lowlatency-x86_64-with-glibc2.34
Python 3.9.7
Installer: DEB

azure-cli 2.18.0 *

Extensions:
azure-devops 0.19.0

```
## Additional Context

Hello,

I am currently working on automating my infrastructure and trying to create a mongodb. I am creating the mongodb via ASO (Azure Service Operator for Kubernetes). After registering the Microsoft.DocumentDB provider I am still getting errors from the CLI when I try to get information on the database that I have created.

Here is an excerpt from my ansible taks which create the mongodb and below the auto generated report from `az feedback`

```yaml
- name: Ensure resource group is {{ state }}.
  k8s:
    namespace: faasaf-playground-{{ app_version }}
    kubeconfig: "{{ playbook_dir }}/../.kube/{{ location }}_config"
    state: "{{ state }}"
    definition:
      apiVersion: resources.azure.com/v1alpha1api20200601
      kind: ResourceGroup
      metadata:
        name: faasaf-playground-{{ location }}
      spec:
        location: "{{ location }}"
  tags:
    - faasaf
    - faasaf.faasaf.io

- name: Ensure MondoDB account is {{ state }}.
  k8s:
    namespace: faasaf-playground-{{ app_version }}
    kubeconfig: "{{ playbook_dir }}/../.kube/{{ location }}_config"
    state: "{{ state }}"
    definition:
      apiVersion: documentdb.azure.com/v1alpha1api20210515
      kind: DatabaseAccount
      metadata:
        name: faasaf-db-account
      spec:
        location: "{{ location }}"
        owner:
          name: faasaf-playground-{{ location }}
        kind: MongoDB
        databaseAccountOfferType: Standard
        locations:
          - locationName: "{{ location }}"
  tags:
    - faasaf
    - faasaf.faasaf.io

- name: Ensure MondoDB database is {{ state }}.
  k8s:
    namespace: faasaf-playground-{{ app_version }}
    kubeconfig: "{{ playbook_dir }}/../.kube/{{ location }}_config"
    state: "{{ state }}"
    definition:
      apiVersion: documentdb.azure.com/v1alpha1api20210515
      kind: MongodbDatabase
      metadata:
        name: faasaf-db-mongodb
      spec:
        location: "{{ location }}"
        owner:
          name: faasaf-db-account
        options:
          autoscaleSettings:
            maxThroughput: 4000
        resource:
          id: faasaf-db-mongodb
  tags:
    - faasaf
    - faasaf.faasaf.io
```
