### ISSUE TITLE
`az login` opens web browser to _AADSTS900144: The request body must contain the following parameter: 'scope'._

### ISSUE THREAD

**Issue by lmmarsano** [Azure/azure-cli#21453]
## Describe the bug

**Command Name**
`az login`

**Errors:**
Web browser opens & displays
```
AADSTS900144: The request body must contain the following parameter: 'scope'.
```
instead of a login prompt.
This wasn't required months ago.
Not sure what to include in `--scope` parameter (nothing seems to work).

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login`

## Expected Behavior
Show login prompt if necessary to allow login as before.

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-debian-11.0, Ubuntu 21.10
Python 3.6.10
Installer: DEB

azure-cli 2.30.0 *

Extensions:
azure-devops 0.22.0
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Could you please share 

- The output of `az cloud show`
- The URL in the browser when it launches
![image](https://user-images.githubusercontent.com/4003950/155912861-3790c5c0-863c-4052-b720-817ec71da35d.png)

**Comment by lmmarsano** [comment]
@jiasli
> Could you please share
> 
> * The output of `az cloud show`
```yaml
$ az cloud show
endpoints:
  activeDirectory: https://login.microsoftonline.com
  activeDirectoryDataLakeResourceId: https://datalake.azure.net/
  activeDirectoryGraphResourceId: https://graph.windows.net/
  activeDirectoryResourceId: https://management.core.windows.net/
  appInsightsResourceId: https://api.applicationinsights.io
  appInsightsTelemetryChannelResourceId: https://dc.applicationinsights.azure.com/v2/track
  attestationResourceId: https://attest.azure.net
  azmirrorStorageAccountResourceId: null
  batchResourceId: https://batch.core.windows.net/
  gallery: https://gallery.azure.com/
  logAnalyticsResourceId: https://api.loganalytics.io
  management: https://management.core.windows.net/
  mediaResourceId: https://rest.media.azure.net
  microsoftGraphResourceId: https://graph.microsoft.com/
  ossrdbmsResourceId: https://ossrdbms-aad.database.windows.net
  portal: https://portal.azure.com
  resourceManager: https://management.azure.com/
  sqlManagement: https://management.core.windows.net:8443/
  synapseAnalyticsResourceId: https://dev.azuresynapse.net
  vmImageAliasDoc: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json
isActive: true
name: AzureCloud
profile: latest
suffixes:
  acrLoginServerEndpoint: .azurecr.io
  attestationEndpoint: .attest.azure.net
  azureDatalakeAnalyticsCatalogAndJobEndpoint: azuredatalakeanalytics.net
  azureDatalakeStoreFileSystemEndpoint: azuredatalakestore.net
  keyvaultDns: .vault.azure.net
  mariadbServerEndpoint: .mariadb.database.azure.com
  mhsmDns: .managedhsm.azure.net
  mysqlServerEndpoint: .mysql.database.azure.com
  postgresqlServerEndpoint: .postgres.database.azure.com
  sqlServerHostname: .database.windows.net
  storageEndpoint: core.windows.net
  storageSyncEndpoint: afs.azure.net
  synapseAnalyticsEndpoint: .dev.azuresynapse.net
```
> * The URL in the browser when it launches

`https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?client_id=04b07795-8ddb-461a-bbee-02f9e1bf7b46`
