### ISSUE TITLE
Azure CLI use_dynamic_install throws Unhandled promise rejection

### ISSUE THREAD

**Issue by briglx** [Azure/azure-cli#21505]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Calling `az config set extension.use_dynamic_install=yes_without_prompt` in the `Azure/CLI` GitHub Action throws the error.

See related issue: https://github.com/Azure/cli/issues/72

**To Reproduce**
- Create GitHub action 
- Create a step that uses azure/CLI@v1 action
- Call `az config set extension.use_dynamic_install=yes_without_prompt`

```
- name: Clean Up Resources
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            
            # Allow Dynamic installation of extensions
            az config set extension.use_dynamic_install=yes_without_prompt
            az automation account delete  .... # The automation extension is not installed by default
```

**Expected behavior**
Code should execute and install uninstalled extensions as needed

**Environment summary**

script execution via docker image mcr.microsoft.com/azure-cli:2.30.0

**Additional context**
