### ISSUE TITLE
az webapp config container set: make option --docker-custom-image-name documentation more explicit 

### ISSUE THREAD

**Issue by meck93** [Azure/azure-cli#21939]
We had a similar as the author of the following issue: https://github.com/Azure/azure-cli/issues/18338#issuecomment-1088732643

It would be great if there could be an example of the `--docker-custom-image-name`. For example, as shown below by appending `(e.g., <registry-name>/<image-name>:<tag>)`.

```
  optionalParameters:
  - name: --docker-custom-image-name -c -i
    summary: The container custom image name and optionally the tag name (e.g., <registry-name>/<image-name>:<tag>)
    description: ''
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acac0890-ff1e-ef72-7715-94988b818426
* Version Independent ID: 7db8a57d-4b68-aa5c-8d7f-52251403f797
* Content: [az webapp config container](https://docs.microsoft.com/en-us/cli/azure/webapp/config/container?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config/container.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webapp/config/container.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**
