### ISSUE TITLE
azure-cli v2 - SweepJob fails when input is a registered dataset

### ISSUE THREAD

**Issue by MarkusDressel** [Azure/azure-cli#22164]
**Describe the bug**
When running a SweepJob (or any other job like commandJob) where inputs should be a registered dataset within the same workspace, the job gets submitted by CLI but at the UI, i get the following error.

```bash
{'code': data-capability.data-capability.FailedToInitializeCapabilitySession.start.UserErrorException, 'message': , 'target': , 'category': UserError, 'error_details': [{'key': NonCompliantReason, 'value': UserErrorException:
	Message: only eval_mount or eval_download modes are supported for v1 legacy dataset for mltable
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "only eval_mount or eval_download modes are supported for v1 legacy dataset for mltable"
    }
}}, {'key': StackTrace, 'value':   File "/opt/miniconda/envs/data-capability/lib/python3.7/site-packages/data_capability/capability_session.py", line 128, in from_cr_config
```
Furthermore, the dataset is not recognized as an input when looking at the summary in the UI, I assume the schema valid for CLI does not match with the one used in the workspace ?
![azure_sweep_fail](https://user-images.githubusercontent.com/50589320/164943914-3119178a-b2d5-4c74-89d5-1b619d2bb3f9.jpg)

The registered dataset is a file dataset. 

Here is the yaml file I am using:
 ```yaml
$schema: https://azuremlschemas.azureedge.net/latest/sweepJob.schema.json
display_name: credit-data-hyper-parameter-sweep-job
experiment_name: credit-data-hyper-parameter-sweep-job
description: Run a hyperparameter sweep job for Sklearn on german credit dataset
sampling_algorithm: random
type: sweep
inputs:
  credit:
    path: azureml:german-credit-dataset-via-jupyter:1
    type: uri_folder
search_space:
  n_estimators:
    type: choice
    values: [50,100,200,300]
  criterion:
    type: choice
    values: [gini, entropy]
  class_weight:
    type: choice
    values: [None, balanced, balanced_subsample]
objective:
  primary_metric: f1-score-test
  goal: maximize
# invoke completions (Ctrl+Space, Cmd+Space) to see the list of compute targets available
compute: azureml:cpu-cluster3
trial:
  code: ./src 
  command: python train.py 
          --data-path ${{inputs.credit}}
          --data-name german_credit_data.csv
          --n_estimators ${{search_space.n_estimators}} 
          --criterion ${{search_space.criterion}} 
          --class_weight ${{search_space.class_weight}}

  # invoke completions (Ctrl+Space, Cmd+Space) to see the list of environments available
  environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu:15
limits:
  max_total_trials: 1
  max_concurrent_trials: 1
  timeout: 10000
```
the command to submit the job is:

` az ml job create --subscription <MASKED> --resource-group <MASKED>--workspace-name <MASKED>--file path/to/file/hyperparameter_tuning.yml --stream `

**To Reproduce**
try to use any registered dataset within a sweepJob configuration

**Expected behavior**
I expect, that the the HyperDrive detects the input dataset correctly.

**Environment summary**
az version
{
  "azure-cli": "2.35.0",
  "azure-cli-core": "2.35.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ml": "2.2.3"
  }
}

**Additional context**
I do have the same issue with commandJobs. While it failed during submitting it via CLI, I was able to get it up and running when I clicked on "edit and submit" in the UI and just added the input dataset via the UI manually. The final yml of this working solution used the old inputs syntax, where datasets where referenced as `datasets: azureml:` rather than `path: azureml:`
But this can not be used if you want to submit a Job via CLI since it is invalid based on the schema.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@MarkusDressel Thank you for reaching out, we are looking into it.

**Comment by sjqnn** [comment]
I'm running into this as well with a commandjob, if anyone wants additional information let me know.

**Comment by MarkusDressel** [comment]
My current assumption is, that azure ml cli v2 introduced new types of datasets (uri-folder and uri file) which can currently only created with the new cli v2 and thus, sweepJob or commandJob are incompatible with 'legacy' datasets uploaded via the UI or python sdk.

**Comment by jackphillipsjmu** [comment]
Still not working with command jobs and CLI ML V2 versions `2.2.x` and above. Reverting the CLI and schema back to `2.1.2` lets the job go through but the Display Name in the Azure ML Studio for the experiment runs are blank. I can still access the run output in the UI via the Run ID column but hopefully a fix comes in soon for later versions.

**Comment by Man-MSFT** [comment]
Adding onto Sam's suggestion above, if you want to use the  backwards compatibility suggestion, please use the new `ml` extension version 2.3.1. https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-cli?tabs=public#installation 
```
inputs:
    my_v1_dataset:
        type: mltable
        path: azureml:myv1ds:1
        mode: eval_mount
```

**Comment by MarkusDressel** [comment]
I can confirm the backward compatibility with a registered V1 dataset in an Azure ML V2 job (ml extension version 2.3.1) using: 

```yaml
inputs:
    my_v1_dataset:
        type: mltable
        path: azureml:myv1ds:1
        mode: eval_mount
```
Would be great if you can reflect that in your documentation.

At least for me, this is my **preferred** solution. While I can understand that **Option 1: Re-create dataset assets as data assets** is the preferred method, this seems like an overkill assuming you have 200 datasets across your workspaces. I hope, that you will auto-convert legacy V1 datasets to V2 datasets once cli V2 gets out of preview.

Thank for your support. Issue can be closed.
