### ISSUE TITLE
az acr build - agent ip address

### ISSUE THREAD

**Issue by romanzdk** [Azure/azure-cli#22920]
Until now we were building and pushing Docker image into ACR (that had public access enabled) using Microsoft-hosted DevOps agent and everything was perfect.

However, we need to make ACR accessible only from selected networks, so I thought I gather IP address of the current agent and add a firewall rule to the ACR. This approach works well for other Azure resources (e.g. KeyVault), however, for some reason when using with ACR I am getting an error when calling `az acr build` command.

The tasks:

```yaml
  - task: AzureCLI@2
    inputs:
      azureSubscription: ${{ parameters.svc_connection }}
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        ip=$(curl -s http://ipinfo.io/ip)
        echo "Agent IP: $ip"
        az acr network-rule add --resource-group ${{ parameters.rg_name }} --name <acr-name> --ip-address $ip
        sleep 15

  - task: AzureCLI@2
    inputs:
      azureSubscription: ${{ parameters.svc_connection }}
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        ip=$(curl -s http://ipinfo.io/ip)
        echo "Agent IP: $ip"
        az acr build -t $(imageName):latest -r <acr-name> --subscription $(subscription--name) .
        ip=$(curl -s http://ipinfo.io/ip)
        echo "Agent IP: $ip"
```

The error:

`failed to login, ran out of retries: failed to set docker credentials: Error response from daemon: Get "https://***/v2/": denied: client with IP 'xx.xx.xx.xx' is not allowed access. Refer https://aka.ms/acr/firewall to grant access.`

The strange thing is, that ip address retrieved from that curl command is completely different from the one in the error and I have no idea how is it possible? How to overcome this, please?
