### ISSUE TITLE
az ml job create should respect .gitignore files in parent directories

### ISSUE THREAD

**Issue by jamescrowley** [Azure/azure-cli#22967]
**Related command**
az ml job create

**Is your feature request related to a problem? Please describe.**
When running `az ml job create` for a pipeline, folders like __pycache__ are uploaded into the snapshot from every component in the pipeline. 

These are excluded in a parent directory .gitignore (the same directory the pipeline yaml is defined in), and yet the CLI does not respect these. 

I see reference in the docs to .amlignore/.gitignore - https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-machine-learning-pipelines#submit-the-pipeline - but it would appear you have to place a gitignore in the folder of every component?

**Describe the solution you'd like**
For the CLI to respect the .gitignore hierarchy.

**Comment by luigiw** [comment]
Hello @jamescrowley .gitignore files are respected by AzureML CLI v2. Can you share your job YAML file and the folder structure of your code folder?

**Comment by jamescrowley** [comment]
folder structure:

```
pipelines
    components
        drop_band
            __pycache__
            .gitignore - <-- works here
            main.py
        drop_band.yml
    .gitignore <-- doesn't work here
    pipeline.yml
.gitignore <-- doesn't work here
```

pipeline yaml:
```
$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: pipeline
experiment_name: default

settings:
  default_datastore: azureml:aml_data_bronze
  default_compute: azureml:aml-cluster-cpu

inputs:
  rgba_input_file:
    type: uri_file
    mode: ro_mount

outputs:
  drop_band_output:
    path: azureml://datastores/aml_data_bronze/paths/azureml/${{name}}/drop_band_output/
    mode: rw_mount
jobs:
  drop_band:
    type: command
    component: file:./components/drop_band.yml
    inputs:
      rgba_input_file: ${{parent.inputs.rgba_input_file}}
    outputs:
      output_folder: ${{parent.outputs.drop_band_output}}

```

job yaml:

```
$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: drop_band
display_name: drop_band
version: 1

inputs:
  rgba_input_file:
    type: uri_file

outputs:
  output_folder:
    type: uri_folder

code: ./drop_band

environment:
  conda_file: ../conda.yml
  image: continuumio/miniconda3

command: >-
  python3 main.py 
    --i ${{inputs.rgba_input_file}}
    --o ${{outputs.output_folder}}
```


results in UI, showing __pycache__ being uploaded

<img width="919" alt="Screenshot 2022-06-23 at 09 59 44" src="https://user-images.githubusercontent.com/509533/175260541-edf9001d-1e72-4811-9a57-75ab0f501c1c.png">
