### ISSUE TITLE
az ml cli v2 pipeline yml does not support keyword 'is_deterministic'

### ISSUE THREAD

**Issue by MarkusDressel** [Azure/azure-cli#23406]
**Related command**

**Describe the bug**
I want to run an azure ml pipeline using azure-cli v2. The steps should be non-deterministic (in sdk = 'allow_reuse'=False). Based on the pipeline schema, this should be set using 
```yaml
is_deterministic: false 
```
which is not accepted when submitting the job using
```bash
az ml job create -f pipeline.yml --web
```
it throws an unrelated error:
```bash
Met error <class 'TypeError'>:ParameterizedParallel.__init__() got an unexpected keyword argument 'environment'
```
When submitting the job without setting deterministic, the pipeline works fine (but being not deterministic)
Here is the pipeline yml definition I use:

```yaml
$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
compute: azureml:cpu-cluster
jobs:
  scrape:
    code: ./src
    command: python run.py --dataset_path ${{inputs.datainput}}
    environment: azureml:my_environment@latest
    inputs:
      datainput:
        type: uri_folder
        path: azureml://datastores/workspaceblobstore/paths/path/to/my/folder/
    is_deterministic: false # without this - pipeline works fine (not deterministic)
```

**To Reproduce**
Create any pipeline with constant input parameters and no explicit output. Try to make it deterministic using above yml file.

**Expected behavior**
Setting 'is_deterministic: false' should be a valid entry and error is **not** raised.

**Environment summary**
```bash
az version
```
outputs:
```bash
{
  "azure-cli": "2.37.0",
  "azure-cli-core": "2.37.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ml": "2.4.1"
  }
}
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@MarkusDressel We are looking into it and get back to you for any additional information.

**Comment by MarkusDressel** [comment]
@SaurabhSharma-MSFT are there any updates on this topic? It is really annoying that the az ml cli v2 does not allow to set this parameter while the python sdk has this feature.

**Comment by zhengfeiwang** [comment]
@MarkusDressel There is an implementation bug and we already created work item internally tracking on it.

To workaround your issue, please try moving "is_deterministic" under "jobs.scrape.component", and the YAML should look like below:

```yaml
$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
compute: azureml:cpu-cluster
jobs:
  scrape:
    component:
      code: ./src
      command: python run.py --dataset_path ${{inputs.datainput}}
      environment: azureml:my_environment@latest
      inputs:
        datainput:
          type: uri_folder
      is_deterministic: false
    inputs:
      datainput:
        type: uri_folder
        path: azureml://datastores/workspaceblobstore/paths/path/to/my/folder/
```
