### ISSUE TITLE
Survey message printed to `stderr`

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#23787]
I have the same problem here. When I use Azure CLI in an Azure DevOps Pipeline, the following text is written to Std Error:
```
Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```
although I set the environment variable `AZURE_CORE_ONLY_SHOW_ERRORS` to `true`.

This makes my pipeline job fail then. Also see https://github.com/microsoft/azure-pipelines-tasks/issues/16840.

_Originally posted by @svdHero in https://github.com/Azure/azure-cli/issues/16949#issuecomment-1237024499_

**Comment by jiasli** [comment]
@svdHero, could you let us know which command that you run triggered this message?

**Comment by svdHero** [comment]
@jiasli Thank you for creating this new issue. I always thought it was `az login`, but that was a red herring. The guilty one actually is `az --version` which writes to StdError.

In Azure DevOps, this pipeline succeeds:
```yaml
name: debugging
trigger: none
stages:
- stage: debugging
  variables:
    AZURE_CORE_ONLY_SHOW_ERRORS: true
  pool:
    vmImage: ubuntu-20.04
  jobs:
    - job: Run_Debugging
      steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'my-service-connection'
            scriptType: bash
            failOnStandardError: true
            scriptLocation: inlineScript
            inlineScript: |
              az account show
```
but this pipeline fails:
```yaml
name: debugging
trigger: none
stages:
- stage: debugging
  variables:
    AZURE_CORE_ONLY_SHOW_ERRORS: true
  pool:
    vmImage: ubuntu-20.04
  jobs:
    - job: Run_Debugging
      steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'my-service-connection'
            scriptType: bash
            failOnStandardError: true
            scriptLocation: inlineScript
            inlineScript: |
              az --version
```

So for me the workaround is to just remove `az --version`. However, this still is a bug, or at least unexpected behaviour.
