### ISSUE TITLE
`az keyvault network-rule add` prints progress status to `stderr` even when `only_show_errors` is set to `true`

### ISSUE THREAD

**Issue by svdHero** [Azure/azure-cli#23801]
**Related command**
`az keyvault network-rule add`

**Describe the bug**

The command writes the following progress to StdErr, although the environment variable `AZURE_CORE_ONLY_SHOW_ERRORS` flag is set to `true`:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    13  100    13    0     0     95      0 --:--:-- --:--:-- --:--:--    94
100    13  100    13    0     0     95      0 --:--:-- --:--:-- --:--:--    94
```

**To Reproduce**
Run the following Azure Pipeline
```yaml
name: debugging
trigger: none
stages:
- stage: debugging
  variables:
    AZURE_CORE_ONLY_SHOW_ERRORS: true
  pool:
    vmImage: ubuntu-20.04
  jobs:
    - job: Run_Debugging
      steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'my-service-connection'
            scriptType: bash
            failOnStandardError: true
            scriptLocation: inlineScript
            inlineScript: |
              vaultName="my-key-vault"
              currentIp=$(curl http://ifconfig.me)
              az keyvault network-rule add --name $vaultName --ip-address $currentIp
```
**Expected behavior**
No output from Azure CLI and a succeeding pipeline run.

**Actual behavior**
Progress output to StdErr and a failing pipeline run.

**Environment summary**
CLI version 2.39.0 via Azure DevOps Pipeline.
