### ISSUE TITLE
Missing features in az ml environment CLIv2 that were present in v1

### ISSUE THREAD

**Issue by tphilley** [Azure/azure-cli#24232]
**Related command**
az ml environment create

**Is your feature request related to a problem? Please describe.**
When creating an environment with a Docker image that is located in a private registry, there is no current way to authenticate with the private registry in the YAML configuration file. Trying to create the image results in an "Unauthorized" error message, as we are not able to pass in credentials.

**Describe the solution you'd like**
In the Azure ML Python SDK v1, there is an option to define a private registry address as well as username and password. Here is the "fastai" demo code:
```
fastai_env.docker.base_image_registry.address = "myregistry.azurecr.io"
fastai_env.docker.base_image_registry.username = "username"
fastai_env.docker.base_image_registry.password = "password"
```
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/ml-frameworks/fastai/fastai-with-custom-docker/fastai-with-custom-docker.ipynb

Please include options in the Environment YAML configuration (as well as the SDKv2) to match existing features in the Python SDK v1. 

**Describe alternatives you've considered**
As a work-around, we are currently using the SDK v1 to register the environment that uses a private registry. After the environment has been registered with v1, we can use the CLI v2 to perform training, model deployments, etc.

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
Adding Service team to look into this ask. 

@azureml-github Could you please look into this feature ask once you get a chance ?

**Comment by singankit** [comment]
Thanks @tphilley for reaching out. To achieve same functionality, CLIv2 provides workspace connections. Workspace connections provide a secure way to provide credentials to private registry. Examples can be found [here](https://github.com/Azure/azureml-examples/blob/main/cli/resources/connections/container-registry-managed-identity.yml). Once connection is created it will automatically be picked up by the environment during build phase.

Sharing sample yaml to create a connection to container registry.
```yaml
name: test_ws_conn_name
type: container_registry
target: testacr.azurecr.io
credentials:
  type: username_password
  username: dummy
  password: dummy
```

**Comment by tphilley** [comment]
Awesome, thank you for that. I haven't been able to find a schema for the sample yaml you provided. Is there a published schema for different credential types?

**Comment by singankit** [comment]
Unfortunately, the schemas for the credentials are not published. I will work with the team to publish them during upcoming release. Meanwhile sharing the schemas for credentials below:

PAT Credential Configuration
```yaml
credentials:
  type: pat
  pat: dummy_pat
```
Username Password Credential Configuration

```yaml
credentials:
  type: username_password
  username: dummy
  password: dummy
```
Managed Identity Credential Configuration

```yaml
credentials:
  type: managed_identity
  client_id: client_id
  resource_id: resource_id
```

Service Principal Credentials Configuration

```yaml
credentials:
  type: service_principal
  client_id: client_id
  client_secret: PasswordPlaceHolder
  tenant_id: tenant_id
```
