### ISSUE TITLE
"error: docker invalid reference format" when using

### ISSUE THREAD

**Issue by tdevopsottawa** [Azure/azure-cli#24255]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az acr network-rule add

**Describe the bug**
Attempting to use Azure CLI in a GitHub action using the official GitHub actions CLI to whitelist an IP address through the ACR firewall, with the following code:
```
      - name: Whitelist Runner IP
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az acr network-rule add --name retailde --ip-address <redacted>
```
results in: `Error: Error: docker: invalid reference format.`

**To Reproduce**
Outlined above

**Expected behavior**
That the process would work.

**Environment summary**
Running on GitHub's ubuntu-latest GitHub actions runner.

**Additional context**
This piece of code worked flawlessly for a long time but suddenly stopped working despite no changes made to the workflow.
