### ISSUE TITLE
az container create returns an internal server error

### ISSUE THREAD

**Issue by stevenjh** [Azure/azure-cli#26001]
**Related command**
`az container create --resource-group my-resource --file aci-single-container-example.yaml`

**Describe the bug**
Running the above command returns the following error: `(InternalServerError) Encountered an internal server error. The tracking activity id is 'c32bf750-e356-49c8-93a9-7f40059f3297', correlation id is '7d842e62-8376-4ffa-a466-72ce7a1afd62'.`
I'm at  dead end trying to follow this and resolve.

**Expected behavior**
Container will be created

**Environment summary**
Running from WSL bash and powershell
```
azure-cli                         2.40.0 *

core                              2.40.0 *
telemetry                          1.0.8

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1
```

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by SaurabhSharma-MSFT** [comment]
@stevenjh Are you referring to any documents or using any sample yaml file.  Is it possible for you to share the yaml file ?

**Comment by stevenjh** [comment]
Hi @SaurabhSharma-MSFT , loosely based on https://learn.microsoft.com/en-us/azure/container-instances/container-instances-vnet

One step I found odd, prior to the error that I've opened this issue against was an error
`(InaccessibleNetworkResource) The client 'xxx-xxx' with object id 'xxx-xxx' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourceGroups/providers/read' over scope '/subscriptions/xxxxxx-xxxxxxx/resourcegroups/RESOURCE-GROUP/providers/Microsoft.Network' or the scope is invalid. If access was recently granted, please refresh your credentials.`

Assigning the  'Azure Container Instance Service - Enterprise Application' roles to the RESOURCE-GROUP resolved this.

Below is the yaml (with identifying portions changed):
``` yaml
apiVersion: '2021-07-01'
location: 'australiaeast'
name: 'test-project'
identity:
  type: "UserAssigned"
  userAssignedIdentities:
    {
      '/subscriptions/xxxxxx-xxxxxxx/resourcegroups/RESOURCE-GROUP/providers/Microsoft.ManagedIdentity/userAssignedIdentities/MANAGED-IDENTITY': {}
    }
properties:
  containers:
  - name: 'test-project'
    properties:
      image: ourregistry.azurecr.io/our-lib:1.2.3 
      command: 
      - 'python3 do-stuff.py --flag'
      ports:
      - port: 80
      resources:
        requests:
          cpu: 1.0
          memoryInGB: 1.5
      volumeMounts: # Array of volume mounts for the instance
      - name: 'ourstorageaccount'
        mountPath: '/mount/'
        readOnly: false
      environmentVariables:
        - name: 'working_dir'
          value: '/mount/test-project/do_stuff_1'

  ipAddress:
    type: Private
    ports:
    - protocol: tcp
      port: '80'
  osType: Linux
  volumes:
  - name: 'ourstorageaccount'
    azureFile:
      shareName: 'testing'
      readOnly: false
      storageAccountName: 'ourstorageaccount'
      storageAccountKey: 'xxxxxxxxxxxxxxxxxxxxx'  
  restartPolicy: never
  subnetIds:
    - id: '/subscriptions/xxxxxx-xxxxxxx/resourceGroups/RESOURCE-GROUP/providers/Microsoft.Network/virtualNetworks/dev-vnet-01'
      name: 'dev-vnet-aci'
tags: {}
type: Microsoft.ContainerInstance/containerGroups
```

**Comment by stevenjh** [comment]
Hi @navba-MSFT & @SaurabhSharma-MSFT,
Was there any additional insight you're able to offer off the back of these internal server error ids?

Thanks,
Steven

**Comment by SaurabhSharma-MSFT** [comment]
@stevenjh sorry for delay on this one.  I will look into this and get back to you as soon as possible.

**Comment by SaurabhSharma-MSFT** [comment]
@stevenjh I am seeing the same error and currently investigating the cause.  I will update you accordingly.

**Comment by SaurabhSharma-MSFT** [comment]
@stevenjh You need to make sure your subnet is delegated to Azure Container Instances before creating the instance. You can validate that on Azure Portal as shown below - 
![image](https://user-images.githubusercontent.com/38112130/232151434-c03452cc-84d9-4fa6-aa8f-85e21974663a.png)
I have tried this and it worked all good.
Please let me know if you have any other questions.

**Comment by stevenjh** [comment]
/unresolve

Hi @SaurabhSharma-MSFT , apologies for the slow reply and thank for checking.

I've reviewed that the subnet `dev-vnet-aci` that was being delegated to the `Microsoft.ContainerInstance/containerGroups' service, it was already assigned.

I'm already successfully running containers with the same configuration when defining parameters in the command line, I'm attempting to move the config to YAML as a first step to defining multi-container workflows which is what's making this such a mystery.

Thanks again

**Comment by SaurabhSharma-MSFT** [comment]
@stevenjh In that case I suggest you to please open a [Azure Support Ticket](https://aka.ms/azsupt) so that a support engineer can check further on the backend telemetry to understand the root cause as I don't have access to the backend logs. In case you have limitations in your support plan to open support ticket please let me know.

**Comment by stevenjh** [comment]
Thanks so much @SaurabhSharma-MSFT , my subscription is managed by our cloud service provider so I'm unable to log support requests.

If there's another way to review this it's appreciated.

**Comment by SaurabhSharma-MSFT** [comment]
@stevenjh Sorry for the delay, let me check internally.  I will get back to you on the same.

**Comment by stevenjh** [comment]
Hi @SaurabhSharma-MSFT, I engaged with our Cloud service provider and they reviewed the yaml and spotted an error in it for the `subnetIds` block, my `id` pointed to the vnet, not the subnet.

```YAML
 subnetIds:
    - id: '/subscriptions/xxxxxx-xxxxxxx/resourceGroups/RESOURCE-GROUP/providers/Microsoft.Network/virtualNetworks/dev-vnet-01'
      name: 'dev-vnet-aci'
```
needed to be
```YAML
 subnetIds:
    - id: '/subscriptions/xxxxxx-xxxxxxx/resourceGroups/RESOURCE-GROUP/providers/Microsoft.Network/virtualNetworks/dev-vnet-01/subnets/dev-vnet-aci'
      name: 'dev-vnet-aci'
```

Thanks for your help and maybe this error can be caught better in the future.
