### ISSUE TITLE
az webapp deployment source config-zip creates sub folder in linux web app

### ISSUE THREAD

**Issue by worldpwn** [Azure/azure-cli#26060]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

```bash
az webapp deployment source config-zip --subscription <sub-id> --resource-group <rg-name> --name <app-name> --src <path-to-zip-file>
```
**Describe the bug**
Zip deployment using azure cli will create a parent folder in wwwroot.

**To Reproduce**

Deploy Linux web app in Azure using bicep:

```bicep

param location string = resourceGroup().location

resource hostingPlan 'Microsoft.Web/serverfarms@2020-12-01' = {
  name: 'test'
  location: location
  kind: 'linux'
  properties: {
    reserved: true
  }
  sku: {
    name: 'F1'
    capacity: 1
  }
}

resource appService 'Microsoft.Web/sites@2021-03-01' = {
  name: 'test'
  location: location
  properties: {
    serverFarmId: hostingPlan.id
    httpsOnly: true
    siteConfig: {
      ftpsState: 'Disabled'
      healthCheckPath: '/'
      http20Enabled: true
      netFrameworkVersion: 'v7.0'
      linuxFxVersion: 'DOTNETCORE|7.0'
    }
  }
}

```
Create a folder dist_empty with an index.html file in it.
Now run commands:
```bash
> zip -r dist_empty.zip dist_empty
> az webapp deployment source config-zip --subscription <sub-id> --resource-group <rg-name> --name <app-name> --src dist_empty.zip
```
After deployment the folder structure in `wwwroot` will be:
<img width="354" alt="Screenshot 2023-04-06 at 13 51 30" src="https://user-images.githubusercontent.com/6351780/230369626-aa79f5ce-af7b-4076-992b-ea3d3f2243d0.png">

**Expected behavior**
The expected behavior is that `wwwroot` will have an index.html file.

**Environment summary**
Mac OS Ventura 13.2.1, azure-cli 2.35.0, zsh terminal

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by worldpwn** [comment]
I updated the `azure cli` to 2.47.0 and the result is the same. 

> Hi @worldpwn,
> 
> 2.35.0 is not the latest Azure CLI(2.47.0).
> 
> Please upgrade to the latest Azure CLI version by following https://learn.microsoft.com/en-us/cli/azure/update-azure-cli.

I updated the `azure cli` to 2.47.0 and the result is the same.

**Comment by DmitryLukyanov** [comment]
I see the same behavior

**Comment by DmitryLukyanov** [comment]
It looks like there is a similar command in preview `az webapp deploy --help` that allows configuring `--target-path` or `--src-path`, but is there approach in RC? And what is a recommended way to solve this issue?

**Comment by tulikac** [comment]
I was able to repro this and it is an expected behavior. The problem is that when you use the zip command (or tar command on Windows), it creates a folder called dist_empty and has the index.html file in it. This is the structure
C:\dist_empty.zip
     dist_empty
           Index.html

On App Service, we just extract the zip and therefore get the dist_empty folder as well. To avoid the issue, create a zip which only has the code files in it and then deploy to App Service.

**Comment by DmitryLukyanov** [comment]
@tulikac , it looks like you're right. Fixed on my side then

**Comment by seligj95** [comment]
Closing. Please reopen if any additional feedback or questions.

**Comment by worldpwn** [comment]
In dotnet 8 (IDK WHY) the same deployment GitHub action deploys the app in the root of the `wwwroot`.

```yml
  deploy_test:
    name: Deploy to Test Environment
    runs-on: ubuntu-latest
    needs: [ci, create_environment_t]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.DIST_FOLDER }}
          path: ${{ env.DIST_FOLDER }}
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SP_T }}
      - name: Zip
        run: |
          zip -r dist.zip ${{ env.DIST_FOLDER }} 
      - name: ls
        run: |
          ls
          echo 'CD'
          cd ${{ env.DIST_FOLDER }}
          ls
      - name: Azure WebApp Deploy
        run: >
          az webapp deployment source config-zip 
          --subscription 123
          --resource-group rg-name
          --name app-name 
          --src dist.zip
```
And I have to update bicep:

```bicep
param location string = resourceGroup().location
resource hostingPlan 'Microsoft.Web/serverfarms@2020-12-01' = {
  name: 'test'
  location: location
  kind: 'linux'
  properties: {
    reserved: true
  }
  sku: {
    name: 'F1'
    capacity: 1
  }
}

resource appService 'Microsoft.Web/sites@2021-03-01' = {
  name: 'test'
  location: location
  properties: {
    serverFarmId: hostingPlan.id
    httpsOnly: true
    siteConfig: {
      ftpsState: 'Disabled'
      http20Enabled: true
      netFrameworkVersion: 'v8.0'
      linuxFxVersion: 'DOTNETCORE|8.0'
      appCommandLine: 'dotnet Loremaster.WebAPI.dll'
    }
  }
}
```
