### ISSUE TITLE
az rest inconsistent result in Github actions 

### ISSUE THREAD

**Issue by Naeemedmo** [Azure/azure-cli#26337]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
`az rest`

**Describe the bug**
Running the following command locally generates expected results, but when I run a github action, it results in only one resource group.
```
az rest \
  --method get \
  --url "https://management.azure.com/subscriptions/$subscription_id/resourceGroups" \
  --url-parameters api-version=2020-06-01 \$expand=createdTime
```

**To Reproduce**
- Create a subscription
- Create several resource groups in portal
- Follow the instruction [here](https://github.com/marketplace/actions/azure-login) to setup Github actions such as:

```
name: Azure Resource manager
on: 
  push:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Resource groups'
      run: |
        az rest \
          --method GET \
          --url "https://management.azure.com/subscriptions/$subscription_id/resourceGroups" \
          --url-parameters api-version=2019-10-01 \$expand=createdTime \$select=name,createdTime > resource-groups.json
        more resource-groups.json
      env:
        subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
```
- Compare local results with the workflow. [Here](https://github.com/Naeemedmo/monitored-resourcelab) is my repo where I reproduced this bug.

**Expected behaviour**
The command must return all the resource groups in the subscription. However that is not the case. For the example in the aforementioned repo, locally I receive the following:
```
{
  "value": [
    {
      "createdTime": "2023-04-04T11:14:42.4714202Z",
      "id": "/subscriptions/***/resourceGroups/rg-main",
      "location": "westeurope",
      "name": "rg-main",
      "properties": {
        "provisioningState": "Succeeded"
      },
      "type": "Microsoft.Resources/resourceGroups"
    },
    {
      "createdTime": "2023-04-14T13:04:54.5605494Z",
      "id": "/subscriptions/***/resourceGroups/rg-testwest",
      "location": "westeurope",
      "name": "rg-testwest",
      "properties": {
        "provisioningState": "Succeeded"
      },
      "tags": {
        "duration": "10"
      },
      "type": "Microsoft.Resources/resourceGroups"
    },
    {
      "createdTime": "2023-04-14T10:57:33.4232716Z",
      "id": "/subscriptions/***/resourceGroups/test-new",
      "location": "southcentralus",
      "name": "test-new",
      "properties": {
        "provisioningState": "Succeeded"
      },
      "tags": {
        "duration": "10"
      },
      "type": "Microsoft.Resources/resourceGroups"
    },
    {
      "createdTime": "2023-04-05T20:22:57.6056543Z",
      "id": "/subscriptions/***/resourceGroups/rg-test",
      "location": "eastus",
      "name": "rg-test",
      "properties": {
        "provisioningState": "Succeeded"
      },
      "tags": {
        "duration": "6"
      },
      "type": "Microsoft.Resources/resourceGroups"
    }
  ]
}
```
However the pipeline generates the following (see also [here](https://github.com/Naeemedmo/monitored-resourcelab/actions/runs/4885149130/jobs/8718836256) in step: Remove resource group):
```
{
  "value": [
    {
      "createdTime": "2023-04-04T11:14:42.4714202Z",
      "id": "/subscriptions/***/resourceGroups/rg-main",
      "location": "westeurope",
      "name": "rg-main",
      "properties": {
        "provisioningState": "Succeeded"
      },
      "type": "Microsoft.Resources/resourceGroups"
    }
  ]
}
```

**Environment summary**
My local machine is macOS Ventura 13.2 with the following az version:
```
azure-cli                         2.47.0 *

core                              2.47.0 *
telemetry                          1.0.8

Extensions:
resource-graph                     2.1.0

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location '/opt/homebrew/Cellar/azure-cli/2.47.0/libexec/bin/python'
Extensions directory '/Users/naeeme/.azure/cliextensions'

Python (Darwin) 3.10.11 (main, Apr  7 2023, 07:24:53) [Clang 14.0.0 (clang-1400.0.29.202)]

Legal docs and information: aka.ms/AzureCliLegal
```
As above, the workflow runs on an Ubuntu machine with:
```
azure-cli                         2.48.1

core                              2.48.1
telemetry                          1.0.8

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location '/opt/az/bin/python3'

Extensions directory '/opt/az/azcliextensions'

Python (Linux) 3.10.10 (main, Apr 25 2023, 04:23:10) [GCC 11.3.0]

Legal docs and information: aka.ms/AzureCliLegal
```

**Additional context**
