### ISSUE TITLE
az k8s-configuration flux create -k 'wait: false'

### ISSUE THREAD

**Issue by schdief** [Azure/azure-cli#27747]
**Related command**

az k8s-configuration flux create -k

https://learn.microsoft.com/de-de/cli/azure/k8s-configuration/flux?view=azure-cli-latest#az-k8s-configuration-flux-create-optional-parameters

**Is your feature request related to a problem? Please describe.**
Yes, because the kustomization won't finish reconcilation in case a sub-resource fails as the wait option is always `true`. This is a problem since we have multiple individual deployments within our repo that are synced with a single Kustomization. If any deployment fails, this impacts the reconcilation of all deployments.

```
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  labels:
    clusterconfig.azure.com/is-managed: 'true'
    clusterconfig.azure.com/name: gitops
    clusterconfig.azure.com/namespace: flux-system
    clusterconfig.azure.com/operation-id: 9d1...
spec:
  force: true
  interval: 8m20s
  path: ./clusters/npi
  postBuild: {}
  prune: true
  retryInterval: 10m0s
  serviceAccountName: flux-applier
  sourceRef:
    kind: GitRepository
    name: gitops
    namespace: flux-system
  timeout: 5m0s
  wait: true
```

**Describe the solution you'd like**
I would like to set the value of `wait` to `false`.

**Describe alternatives you've considered**
We could create individual Kustomizations, but then they won't be part of our repository so a restore would be cumbersome. So the only alternative is not using the aks flux extension.

**Additional context**
