### ISSUE TITLE
Azure CLI curl package removed as default in 2.54.0

### ISSUE THREAD

**Issue by kesava9** [Azure/azure-cli#27882]
### Describe the bug

We have noticed that curl is missing in Azure CLI version 2.54.0 which is present in all previous versions as default.

 This can be replicated using following github workflow : 

```
name: AzureCLI
on:
  pull_request:
    branches:
      - main
jobs:
  check-cli-curl:
    runs-on: ubuntu-latest
    steps:
        
    - name: Add the runner
      uses: azure/CLI@v1
      with:
        azcliversion: 2.53.1
        inlineScript: |
          set -x
          IP=`curl https://api.ipify.org`
          echo "RUNNER_IP=$IP" >> $GITHUB_ENV
          
        
    - name: Add the runner
      uses: azure/CLI@v1
      with:
        azcliversion: 2.54.0
        inlineScript: |
          set -x
          IP=`curl https://api.ipify.org`
          echo "RUNNER_IP=$IP" >> $GITHUB_ENV
```

### Related command

curl https://api.ipify.org

### Errors

curl not found in latest version

### Issue script & Debug output

NA

### Expected behavior

It should return IP address

### Environment Summary

2.54.0

### Additional context

<img width="797" alt="image" src="https://github.com/Azure/azure-cli/assets/47521902/a4187115-2874-4047-a896-cd09001c8561">
