### ISSUE TITLE
azure/CLI@v1 Unable to find image 'mcr.microsoft.com/azure-cli:2.55.0' locally

### ISSUE THREAD

**Issue by bigswede74** [Azure/azure-cli#28076]
### Describe the bug

I'm using the azure/CLI@v1 action in a GitHub Action Workflow and docker is unable to pull the azure cli image.

### Related command

```yaml
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}        

    - name: CREATE VM
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az vm create --resource-group ${{ env.RESOURCE_GROUP }}  --name "${{ format('{0}-{1}', github.event.inputs.vm-name, github.run_number) }}"  --admin-username ${{ env.VM_USER }} --admin-password "${{ secrets.AZURE_VM_PWD }}" --location  ${{ github.event.inputs.azure-region }} \
          --image "${{ steps.imageBuilder.outputs.custom-image-uri }}" 
```

### Errors

**Warning:** Unable to fetch all az cli versions, please report it as an issue on https://github.com/Azure/CLI/issues. Output: , Error: Error: The process 'curl' failed with exit code 28
Starting script execution via docker image mcr.microsoft.com/azure-cli:2.55.0
**Error: Error:** Unable to find image 'mcr.microsoft.com/azure-cli:2.55.0' locally
docker: Error response from daemon: Get "https://mcr.microsoft.com/v2/": dial tcp IP_ADDRESS:443: i/o timeout.

### Issue script & Debug output

**Script/Workflow**
```yaml
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}        

    - name: CREATE VM
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az vm create --resource-group ${{ env.RESOURCE_GROUP }}  --name "${{ format('{0}-{1}', github.event.inputs.vm-name, github.run_number) }}"  --admin-username ${{ env.VM_USER }} --admin-password "${{ secrets.AZURE_VM_PWD }}" --location  ${{ github.event.inputs.azure-region }} \
          --image "${{ steps.imageBuilder.outputs.custom-image-uri }}" 
```
**Action Output**
`
Run azure/CLI@v1
  with:
    inlineScript: az vm create --resource-group my-resource-group  --name "az-tenant"  --admin-username user --admin-password "***" --location  westus2 \
  --image "/subscriptions/***/resourceGroups/shared-image-gallery-resource-group/providers/Microsoft.Compute/galleries/shared_image_gallery/images/my-dev/versions/X.X.XX"
    azcliversion: agentazcliversion
  env:
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 

Warning: Unable to fetch all az cli versions, please report it as an issue on https://github.com/Azure/CLI/issues. Output: , Error: Error: The process 'curl' failed with exit code 28
Starting script execution via docker image mcr.microsoft.com/azure-cli:2.55.0
Error: Error: Unable to find image 'mcr.microsoft.com/azure-cli:2.55.0' locally
docker: Error response from daemon: Get "https://mcr.microsoft.com/v2/": dial tcp IP:44[3] i/o timeout.
See 'docker run --help'.

cleaning up container...
Warning: Error response from daemon: No such container: MICROSOFT_AZURE_CLI_1703097876311_CONTAINER

Error: Unable to find image 'mcr.microsoft.com/azure-cli:2.55.0' locally
docker: Error response from daemon: Get "https://mcr.microsoft.com/v2/": dial tcp 20[4])9:443: i/o timeout.
See 'docker run --help'.
`

### Expected behavior

The workflow should be able to pull the correct docker container for the azure cli.

### Environment Summary

azure-cli: 2.55.0

github actiion runner: ubuntu-latest
