### ISSUE TITLE
azure/cli@v2 can't be configured to just use existing / installed az cli?

### ISSUE THREAD

**Issue by johnpetersjr** [Azure/azure-cli#28620]
### Describe the bug

I am trying to utilize the somewhat new GitHub-hosted runners with Azure VNET connectivity, with the azure/cli@v2 action.   I'm also using an OIDC federated credential attached to the managed identity to let this github action / branch use my MI. 

When the GitHub Action runs, it seems like it always tries to go out to the internet and download the cli?  For security concerns, I'd prefer to not let this "private" runner have access to the internet.  My hope is that when I run an az cli command in the azure/cli@v2 action, it should use whatever version is pre-baked into the action, but I'm having no such luck.  Is this a bug, or a feature request, I am not sure?  Is this possible?

### Related command

Here is my github action:
```
name: Azure CLI on a github public runner with vnet connectivity
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  run_az_cli:
    runs-on: my-private-runner
    env:
      client-id: my-managed-identity-guid
      subscription-id: my-subscription-guid
      tenant-id: my-tenant-guid

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Az CLI login # Strangely, this works fine!
        uses: azure/login@v2
        with:
          client-id: my-managed-identity-guid
          subscription-id: my-subscription-guid
          tenant-id: my-tenant-guid

      - name: Run Azure CLI Action simple test - cannot figure out how to make this work
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az version
```

### Errors

```
Warning: Unable to fetch all az cli versions, please report it as an issue on https://github.com/Azure/CLI/issues. Output: , Error: Error: The process 'curl' failed with exit code 28
Starting script execution via docker image mcr.microsoft.com/azure-cli:latest
Error: Error: Unable to find image 'mcr.microsoft.com/azure-cli:latest' locally
docker: Error response from daemon: Get "https://mcr.microsoft.com/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.

cleaning up container...
Warning: Error response from daemon: No such container: MICROSOFT_AZURE_CLI_17111264[16](https://github.com/my-org/my-repo/actions/runs/1111111111/job/2222222222#step:5:17)162_CONTAINER

Error: Unable to find image 'mcr.microsoft.com/azure-cli:latest' locally
docker: Error response from daemon: Get "https://mcr.microsoft.com/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
```

This is normal error, because I do not allow internet outbound access, and I don't want to either ... if I let this subnet out to the internet, it does work fine... is there a way to avoid having to let this action/runner out to the internet to use the hopefully already installed cli?  Or is there just not an az cli installed, and it has to go fetch one each time?

### Issue script & Debug output

See above, --debug provided no more information that was already provided.

### Expected behavior

I would expect to be able to pass some sort of parameter to the azure/cli@v2 to just use the azcliversion that is already installed in the action, so it doesn't try to connect to the internet to get another version?

### Environment Summary

Can't even run az --version, but it's likely whatever is installed in the azure/cli@v2 currently, if I could get to it?

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by MoChilia** [comment]
Hi @johnpetersjr, if the docker image `mcr.microsoft.com/azure-cli:${azcliversion}` is already pulled on your private runner, then azure/cli action will not download it again from the Internet. You can pre-installed the azure-cli image from [mcr](https://mcr.microsoft.com/v2/).

**Comment by johnpetersjr** [comment]
> Hi @johnpetersjr, if the docker image `mcr.microsoft.com/azure-cli:${azcliversion}` is already pulled on your private runner, then azure/cli action will not download it again from the Internet. You can pre-installed the azure-cli image from [mcr](https://mcr.microsoft.com/v2/).

Understood, but it's not really my private runner, it's a GitHub public runner with private network connectivity.  Is there a preemptive action I can execute to have that available on a public runner?

**Comment by MoChilia** [comment]
@johnpetersjr, is it possible for you to access Azure Container registry with your private network? One approach could be to push the azure-cli image to ACR from a computer with outbound Internet access, and then pull it from ACR on the runner with private network connectivity. 
However, this process is complex. Maybe you could simplify by adding `mcr.microsoft.com` to the allowed list for your vnet? Images from MCR are official Microsoft images which are considered secure.

**Comment by johnpetersjr** [comment]
The approach was to use the azure-cli image and run az cli commands, without having to do any extra steps.  Our expectation is the github action image we use is complete, and doesn't need to go download updates/patches from the internet.  A blessed, secure, patched, ready to use image.

We were able to work around this by using a simple run: command on the native github runner's image that magically had az cli on it somehow.  

For reference - some customers run GitHub actions on private runners that have no internet access as a security guardrail.  It would be awesome if the image being used just had everything pre-installed with no need to go out to the internet for additional updates.

**Comment by stan-spotts** [comment]
Thank you for posting your work around!

I just went through Hell because I couldn't even get azure/login@v2 to work. Used the instructions at:
https://docs.github.com/en/organizations/managing-organization-settings/configuring-private-networking-for-github-hosted-runners-in-your-organization

Finally figured out I had to add three additional NSG rules so it could reach login.microsoftonline.com.

But I had a simple step:
```
        - name: Azure CLI script
          uses: azure/cli@v2
          with:
            azcliversion: latest
            inlineScript: |
              az account show
```

And got the same error you reported. Was irritating, to say the least.

```
arning: Unable to fetch all az cli versions, please report it as an issue on https://github.com/Azure/CLI/issues. Output: , Error: Error: The process 'curl' failed with exit code 28
Starting script execution via docker image mcr.microsoft.com/azure-cli:latest
Error: Error: Unable to find image 'mcr.microsoft.com/azure-cli:latest' locally
docker: Error response from daemon: Get "https://mcr.microsoft.com/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
```
So followed what you said and changed it to just:

```
- name: Azure CLI script
          run: |
            az account show
```
and it worked.
