### ISSUE TITLE
[Reference feedback]:

### ISSUE THREAD

**Issue by scyto** [Azure/azure-cli#30843]
### Type of issue

Other (describe below)

### Reference command name

az containerapp compose create

### Feedback

Wow, this is hard to use, i have extensive docker compose exprience.

Is there are documnetation on what compose file items are supported - for example how the heck do i specifiy a volume - i have tried this syntax (as sugged in older stack articles and by MS copilot, but not joy)

Is this actually a supported scenario?

If not maybe a compose to  az containerapp native yaml tranlsator would be a better engineering investment and just drop suppor for compose entirely.

This is the compose i want to run as originally suggested by the image creators

```
services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    volumes:
      - ./data:/root
    network_mode: "host"

    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    network_mode: "host"
    restart: unless-stopped
```

This is where i ended up based on copilot input and a couple fo stack social threads (old) after trying to create container storage account and a file share account, i suspect the volume driver options cannot be translated correclty into azure file share storage or container storage - but maybe with a *full* canonical compose file exmample i might have a hope in hell of figuring this out

```
services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    ports:
      - "21115:21115"
      - "21116:21116"
      - "21116:21116/udp"
      - "21118:21118"
    volumes:
      - rustdeskdekstop-data:/root
    depends_on:
      - hbbr

  hbbr:
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    ports:
      - "21117:21117"
      - "21119:21119"
    volumes:
      - rustdesktop-data:/root

volumes:
  rustdesk-data:
    driver: azure_file
    driver_opts:
      share_name: rustdesktop-data
      storage_account_name: alexbalcontainerdata
      storage_account_key: redacted

```

### Page URL

https://learn.microsoft.com/en-us/cli/azure/containerapp/compose?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/containerapp/compose.yml

### Author

@dbradish-microsoft

### Document Id

d10250cd-c6ca-a9a6-d6e8-b93f81b94ff1
