### ISSUE TITLE
Prettier yaml output from `az aks get-credentials`

### ISSUE THREAD

**Issue by tolu** [Azure/azure-cli#5638]
Using `az aks get-credentials -g <group> -n <name> --file <path>` is very nifty and handy in that it merges the changes into the (potentially) already existing config file.

**But**, it would be even better if the output could be written in a more readable YAML (avoiding `[]` and `{}` and placing each property on a new line as you do when writing by hand).

---

### Environment summary

**Install Method**: MSI
**CLI version**: 2.0.27
**OS version**: Windows 10 (Build 16251.rs3_release.170721-2122
**Shell Type**: cmd.exe 

---
The output produced by the tool, that to me looks more like **unquoted** `json` than `yaml` 😄, could improve on its readability which is everything when looking for errors.

The usage of `[]` and `{}` also confuses me and a lot of YAML validators I've tried that does not seem to be able to parse that format (that might be their problem but still...).

So... **please please please** output more humanly readable `yaml`.

Example output from `az aks get-credentials -g <group> -n <name> --file <path>`
```
{apiVersion: v1, clusters: [{cluster: {certificate-authority-data: REDACTED,
        server: 'https://<REDACTED>.azmk8s.io:443'},
      name: k8s-ps-prod}], contexts: [{context: {cluster: k8s-ps-prod, user: REDACTED},
      name: k8s-ps-prod}], current-context: k8s-ps-prod, kind: Config, preferences: {},
  users: [{name: REDACTED, user: {client-certificate-data: REDACTED,
        client-key-data: REDACTED,
        token: REDACTED}}]}
```

Original file format was (and is the output of using the above in http://www.yamllint.com/)
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: https://<REDACTED>.azmk8s.io:443
  name: k8s-ps-prod
contexts:
- context:
    cluster: k8s-ps-prod
    namespace: kube-system
    user: REDACTED
  name: k8s-ps-prod
current-context: k8s-ps-prod
kind: Config
preferences: {}
users:
- name: REDACTED
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
    token: REDACTED
```
