### ISSUE TITLE
azure_rm_virtualmachine : two network security groups are created instead of one

### ISSUE THREAD

**Issue by scizmeli** [Azure/azure-cli#5925]
Hi, 

I created the virtual machine with the following playbook.  The problem is that I get two Network Security  groups created for the machine. The one I want (testSecurityGroup) is not attached to any interface, the one I don't want (testNIC) IS attached. 
any ideas where I am wrong?
thanks a lot from advance for your kindly help

```
- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: pgeo
      name: testVnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: pgeo
      name: testSubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: testVnet
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: pgeo
      name: testSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
        - name: zumtest
          protocol: Tcp
          destination_port_range: 8888
          access: Allow
          priority: 1003
          direction: Inbound
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: pgeo
      allocation_method: Static
      name: testIP
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: pgeo
      name: testNIC
      virtual_network: testVnet
      subnet: testSubnet
      public_ip_name: testIP
      security_group: testSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: pgeo
      name: test
      vm_size: Standard_B2s
      admin_username: testadmin
      admin_password: testtest
      ssh_password_enabled: false
      ssh_public_keys: 
        - path: /home/testadmin/.ssh/authorized_keys
          key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDta6CbJQjPnBOhJVwZHTfgO9GWOk5A94ewGY97rxzmhX9B+chLZNDkspfsIlxgb/yG4PL4Rh1fdfUZ2zXNTS3YhyWpkTUgyOl14N2EjJlpTaC5so7IycLvG7h71/oYBshkBwesu8zMbfQyyTHdfbojChdOSQFqTSKq6vJqCMlVVyhd6n8HZrAVAKliFvdoW9SAWgcmodnxehA3J7uufj9JQwGUW97+a/ThKyhZSw30/+sXBNT1SdDrIr0jGalqX0NjgNWYQvQCj0onyEHrVTl66QmpcqLnqft55/e7IW/U8ji7TarSgEVUU8a7/f73SWlh1ZAsb7Ht11Pj9EDo005 dffdmeli@crdfagfwnfcrfaffwler"
      network_interfaces: testNIC
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '16.04-LTS'
        version: latest
```

![image](https://user-images.githubusercontent.com/1478968/37965836-228aa2b6-31cf-11e8-8e24-30603d51bb28.png)

---

### Environment summary

Install Method : apt-get
CLI version : azure-cli (2.0.27)
OS version : Ubuntu 16.04
Shell Type : bash
```
```
