### ISSUE TITLE
az container create with yaml file and secureValue fails with not supported before version 2018-06-01

### ISSUE THREAD

**Issue by JasonHaley** [Azure/azure-cli#6643]
**Describe the bug**
When I try to use the az container create with a yaml file it fails when new features like secureValue for an environment variable or connecting to Log Analytics with the message:

az : ERROR: The secure environment variable is not supported before version '2018-06-01'. 
At line:1 char:1 

**To Reproduce**
Create the following yaml file as secure-env.yaml (taken from the docs: https://docs.microsoft.com/en-us/azure/container-instances/container-instances-environment-variables):
```
apiVersion: 2018-06-01
location: westus
name: securetest
properties:
  containers:
  - name: mycontainer
    properties:
      environmentVariables:
        - "name": "SECRET"
          "secureValue": "my-secret-value"
        - "name": "NOTSECRET"
          "value": "my-exposed-value"
      image: nginx
      ports: []
      resources:
        requests:
          cpu: 1.0
          memoryInGB: 1.5
  osType: Linux
  restartPolicy: Always
tags: null
type: Microsoft.ContainerInstance/containerGroups
```
Create the resource group
```
az group create --location westus --name myRG
```
Attempt to create the container with the yaml file:
```
az container create --resource-group myRG --name securetest -f secure-env.yaml
```

**Expected behavior**
The container should be created using the secureValue provided in the yaml file.

**Environment summary**
I'm running Window 10, CLI version 2.0.38 and conatainer (0.1.24)

**Additional context**
The sample code on this page fails too with the same error when trying to connect to Azure Log Analytics: https://docs.microsoft.com/en-us/azure/container-instances/container-instances-log-analytics

The Cloud Shell does seem to work in the Azure Portal but the latest CLI running on my machine does not.
