### ISSUE TITLE
az aks get-credentials corrupts kube config file when cluster with same name is re-created.

### ISSUE THREAD

**Issue by choovick** [Azure/azure-cli#7040]
**Describe the bug**
If AKS cluster created, kubectl credentials obtained then cluster deleted and created again. `az aks get-credentials` will corrupt kubectl config file by creating duplicate records in config file for `clusters` and `users` lists.

**To Reproduce**
Create cluster:
```bash
az group create --name myAKSCluster --location eastus
az aks create --resource-group myAKSCluster --name myAKSCluster --node-count 1 --enable-addons monitoring --generate-ssh-keys
```
Get credentials:
```bash
az aks get-credentials --resource-group myAKSCluster --name myAKSCluster
```

Test kubectl
```bash
kubectl get nodes
```

Delete cluster:
```bash
az group delete --name myAKSCluster --yes
```

Create cluster with same name again:
```bash
az group create --name myAKSCluster --location eastus
az aks create --resource-group myAKSCluster --name myAKSCluster --node-count 1 --enable-addons monitoring --generate-ssh-keys
```

Get credentials:
```bash
az aks get-credentials --resource-group myAKSCluster --name myAKSCluster
```

Test kubectl
```bash
kubectl get nodes
```

Result:
```
kubectl get nodes
error: Error loading config file "/Users/user/.kube/config": error converting *[]NamedCluster into *map[string]*api.Cluster: duplicate name "myAKSCluster" in list: [{myAKSCluster {https://myaksclust-myakscluster-104af6-eb4c3d33.hcp.eastus.azmk8s.io:443 false  [45
```

Content of `~/.kube/config`
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://myaksclust-myakscluster-104af6-eb4c3d33.hcp.eastus.azmk8s.io:443
  name: myAKSCluster
- cluster:
    certificate-authority-data: ...
    server: https://myaksclust-myakscluster-104af6-d618edc6.hcp.eastus.azmk8s.io:443
  name: myAKSCluster
contexts:
- context:
    cluster: myAKSCluster
    user: clusterUser_myAKSCluster_myAKSCluster
  name: myAKSCluster
current-context: myAKSCluster
kind: Config
preferences: {}
users:
- name: clusterUser_myAKSCluster_myAKSCluster
  user:
    client-certificate-data: ...
    client-key-data: ...
    token: ...
- name: clusterUser_myAKSCluster_myAKSCluster
  user:
    client-certificate-data: ....
    client-key-data: ...
    token: ...
```

**Expected behavior**
kubectl should work, upon credentials merge items in lists of users/clusters with the same name should be replaced. Or these should be a replace flag...

**Environment summary**
Installed via brew on mac os. Version:
```
az --version
azure-cli (2.0.43)

acr (2.1.2)
acs (2.2.2)
advisor (0.6.0)
ams (0.2.1)
appservice (0.2.1)
backup (1.2.0)
batch (3.3.1)
batchai (0.4.0)
billing (0.2.0)
cdn (0.1.0)
cloud (2.1.0)
cognitiveservices (0.2.0)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.2)
core (2.0.43)
cosmosdb (0.2.0)
dla (0.2.0)
dls (0.1.0)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.1)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.27)
iot (0.2.0)
keyvault (2.2.1)
lab (0.1.0)
maps (0.3.1)
monitor (0.2.1)
network (2.2.2)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.0)
redis (0.3.0)
reservations (0.3.1)
resource (2.1.1)
role (2.1.2)
search (0.1.0)
servicebus (0.2.1)
servicefabric (0.1.0)
sql (2.1.1)
storage (2.1.1)
vm (2.2.0)

Python location '/usr/local/opt/python/bin/python3.7'
Extensions directory '/Users/apopovich/.azure/cliextensions'

Python (Darwin) 3.7.0 (default, Jul 23 2018, 20:22:55)
[Clang 9.1.0 (clang-902.0.39.2)]

Legal docs and information: aka.ms/AzureCliLegal
```

**Additional context**
As a workaround I have to unset existing users/cluster items using `kubectl config unset` command before getting credentials.
