### ISSUE TITLE
az aks get-credentials error: A different object named {{ name }} already exists in clusters

### ISSUE THREAD

**Issue by ArseniiPetrovich** [Azure/azure-cli#7670]
**Describe the bug**
I have a script that deletes and recreates an AKS cluster. Unfortunately it doesn't work since when I'm trying to recreate cluster and get it creds i receive a following error:
`A different object named {{ name }} already exists in clusters`
This error occurs even if I recreate a resource group. I guess Azure stores somehow a name of deleted cluster. How should I properly delete it?

**To Reproduce**
```bash
az group create --name ${cluster}_rg --location $region
az aks create --resource-group ${cluster}_rg --name $cluster --node-count $nodes --enable-addons monitoring --generate-ssh-keys
az aks delete --resource-group ${cluster}_rg --name $cluster
az ad app delete --id http://$cluster
az group delete --name ${cluster}_rg
rm ~/.azure/aksServicePrincipal.json
az group create --name ${cluster}_rg --location $region
az aks create --resource-group ${cluster}_rg --name $cluster --node-count $nodes --enable-addons monitoring --generate-ssh-keys
az aks get-credentials -a --resource-group ${cluster}_rg --name $cluster
```

**Expected behavior**
I receive valid credentials to use it with the further commands.

**Environment summary**
Azure CLI (2.0.47) installed via apt-get on bash.

**Comment by doelleri** [comment]
I got around this by editing my kube config (~/.kube/config). Remove the existing cluster, context, and user for the given name. You will then be able to run `az aks get-credentials` again.

```
clusters:
- cluster:
    certificate-authority-data: <encoded data>
    server: <url>
  name: <name to delete>

contexts:
- context:
    cluster: <name to delete>
    user: <user to delete>
  name: <name to delete>

users:
- name: <user to delete>
  user:
    client-certificate-data: <encoded data>
    client-key-data: <encoded data>
    token: <hash>
```
