### ISSUE TITLE
Live Test results should be sliced to only message the relevant owners

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#8373]
Currently, the Live Test system sends the list of all failures to everyone on its distribution list. This noise to the team results in live test results being less relevant. If any given day you can expect 60-70 failures, are you going to diligently search for the one failure that's new that wasn't there before?  There's another issue opened to improve live test failure triage, but it would be helpful if we could configure who receives what failures. For example, on a daily basis, I am primarily concerned with Monitor and Network failures, particularly new ones. Service teams are ONLY concerned with their live test failures.

As a naïve solution, it seems we could maintain a mapping of partial paths to aliases as one way of accomplishing this. For example:
```YAML
- alias: myalias
   watch: 
    - *.command_modules.network.*
    - *.command_modules.monitor.*
```
