### ISSUE TITLE
ACI deployment with --file ignores location specified in YAML

### ISSUE THREAD

**Issue by jberezanski-mdg** [Azure/azure-cli#8449]
**Describe the bug**
When deploying a container group using `az container create -g mygroup -f spec.yml`, the container group is deployed into the location of the resource group, not the location specified in the YAML file.

**To Reproduce**
```
az group create -l eastus -n mygroup
notepad spec.yml

apiVersion: 2018-10-01
location: westus2
name: test-westus2
properties:
  containers:
  - name: test-westus2
    properties:
      image: nginx:latest
      resources:
        requests:
          cpu: 1
          memoryInGb: 1
          gpu: null
      ports:
      - port: 80
  osType: Linux
  restartPolicy: OnFailure
  ipAddress:
    type: Public
    ports:
    - port: 80
tags: null
type: Microsoft.ContainerInstance/containerGroups

az container create -g mygroup -f spec.yml
```

output:
```
{
  "id": "/subscriptions/<id>/resourceGroups/mygroup/providers/Microsoft.ContainerInstance/containerGroups/test-westus2",
  "identity": null,
  "kind": null,
  "location": "eastus",
  "managedBy": null,
  "name": "test-westus2",
(…)
```

**Expected behavior**
The container group is created in the West US 2 location (as specified in the YAML file). The location of the resource group should be irrelevant.

**Environment summary**
az --version: 2.0.57
install method: Chocolatey (`cinst -y azure-cli`)
OS: Windows 10 1803
shell: PowerShell 5.1

**Additional context**
The container group location is respected if it is passed on the command line via `--location`:
```
az container create -g mygroup -l westus2 -n test2 --image nginx:latest
az container create -g mygroup -l westus2 -f spec.yml
```
