### ISSUE TITLE
Format of index.yaml for acr helm repo

### ISSUE THREAD

**Issue by vazexqi** [Azure/azure-cli#8714]
I've notice that the format for `url` key in the generated index.yaml for acr helm repo uses relative paths. For instance, following the example at https://docs.microsoft.com/en-us/azure/container-registry/container-registry-helm-repos (to insert the sample wordpress chart) generates the following index.yaml cache. Notice that the `url` key is  `_blobs/wordpress-5.2.5.tgz`. This would have to be concatenated with the `contextPath` and the root domain to get the full URL.

```
apiVersion: v1
entries:
  wordpress:
  - acrMetadata:
      manifestDigest: sha256:08ef434162070bba4256414c80b001d15b7503ef2a1a4fa1f60bab174f80d4d7
    appVersion: 5.1.0
    created: "2019-03-06T16:59:25.8892193Z"
    description: Web publishing platform for building blogs and websites.
    digest: e0f315e609e02fd4798bed33d56267fd68f5e45dae2015b8895474178e6cc8e4
    engine: gotpl
    home: http://www.wordpress.com/
    icon: https://bitnami.com/assets/stacks/wordpress/img/wordpress-stack-220x234.png
    keywords:
    - wordpress
    - cms
    - blog
    - http
    - web
    - application
    - php
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: wordpress
    sources:
    - https://github.com/bitnami/bitnami-docker-wordpress
    urls:
    - _blobs/wordpress-5.2.5.tgz
    version: 5.2.5
generated: "2019-03-06T18:44:57Z"
serverInfo:
  contextPath: /helm/v1/repo
```

Is it possible to configure this to use full paths? I didn't find any options on the az CLI. This would be more inlined with how other repos like https://azure-samples.github.io/helm-charts/index.yaml do it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bed94c3-b7a7-40d4-0102-8c9b1f1145ca
* Version Independent ID: 2d4ac8bd-dc7a-236c-56db-7f0e1ce0fd05
* Content: [az acr helm](https://docs.microsoft.com/en-us/cli/azure/acr/helm?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**
